export interface CategorySeedItem {
  id: string;
  name_uz: string;
  slug: string;
  icon: string;
  parent_id?: string | null;
  sort_order: number;
}

export interface CatalogSpec {
  id: string;
  name_uz: string;
  slug: string;
  icon: string;
  description: string;
  listing_types: string;
  sort_order: number;
}

export const CATALOGS_LIST: CatalogSpec[] = [
  {
    id: 'services',
    name_uz: 'Xizmatlar',
    slug: 'xizmatlar',
    icon: 'Wrench',
    description: 'Ustalar, xizmat ko‘rsatuvchilar va maishiy xizmatlar',
    listing_types: 'SERVICE_OFFER,SERVICE_REQUEST',
    sort_order: 1,
  },
  {
    id: 'jobs',
    name_uz: 'Ish e’lonlari',
    slug: 'ish-elonlari',
    icon: 'Briefcase',
    description: 'Vakansiyalar, bo‘sh ish o‘rinlari va mutaxassis rezyumelari',
    listing_types: 'JOB_OPENING,JOB_SEEKER',
    sort_order: 2,
  },
];

export interface ParentCategorySpec {
  id: string;
  catalog_id?: string;
  name_uz: string;
  slug: string;
  icon: string;
  subs: { id: string; name_uz: string; slug: string }[];
}

export const CATEGORIES_CATALOG: ParentCategorySpec[] = [
  {
    id: 'cat_gozallik',
    name_uz: "Go'zallik, salomatlik",
    slug: 'gozallik-salomatlik',
    icon: 'Sparkles',
    subs: [
      { id: 'cat_manikyur', name_uz: 'Manikyur-pedikyur', slug: 'manikyur-pedikyur' },
      { id: 'cat_sartaroshxona', name_uz: 'Sartaroshxona xizmatlari', slug: 'sartaroshxona-xizmatlari' },
      { id: 'cat_kirpik_qosh', name_uz: 'Kirpiklar, qoshlar', slug: 'kirpiklar-qoshlar' },
      { id: 'cat_boyanish', name_uz: "Doimiy bo'yanish", slug: 'doimiy-boyanish' },
      { id: 'cat_kosmetologiya', name_uz: 'Kosmetologiya', slug: 'kosmetologiya' },
      { id: 'cat_epilyatsiya', name_uz: 'Epilyatsiya', slug: 'epilyatsiya' },
      { id: 'cat_makiyaj', name_uz: 'Makiyaj', slug: 'makiyaj' },
      { id: 'cat_massaj_spa', name_uz: 'SPA xizmatlari, massaj', slug: 'spa-xizmatlari-massaj' },
      { id: 'cat_tatuirovka', name_uz: 'Tatuirovka, pirsing', slug: 'tatuirovka-pirsing' },
      { id: 'cat_psixologiya', name_uz: 'Psixologiya', slug: 'psixologiya' },
      { id: 'cat_parhezshunoslik', name_uz: 'Parhezshunoslik', slug: 'parhezshunoslik' },
      { id: 'cat_fitnes_yoga', name_uz: 'Fitnes, yoga', slug: 'fitnes-yoga' },
      { id: 'cat_ish_joyi_ijara', name_uz: 'Ish joyini ijaraga olish', slug: 'ish-joyini-ijaraga-olish' },
      { id: 'cat_gozallik_boshqa', name_uz: "Boshqa go'zallik xizmatlari", slug: 'boshqa-gozallik' },
    ],
  },
  {
    id: 'cat_tamirlash',
    name_uz: "Ta'mirlash va bezash",
    slug: 'tamirlash-va-bezash',
    icon: 'Paintbrush',
    subs: [
      { id: 'cat_kalit_topshirish', name_uz: 'Kvartiralar va uylarni kalitlarga topshirish', slug: 'kvartiralar-uylar-kalit' },
      { id: 'cat_ichki_dizayn', name_uz: 'Ichki dizayn', slug: 'ichki-dizayn' },
      { id: 'cat_santexnika', name_uz: 'Santexnika', slug: 'santexnika' },
      { id: 'cat_elektrik', name_uz: 'Elektrika', slug: 'elektrika' },
      { id: 'cat_mebel_tamirlash', name_uz: "Mebel yig'ish va ta'mirlash", slug: 'mebel-yigish-tamirlash' },
      { id: 'cat_deraza_balkon', name_uz: 'Derazalar va balkonlar', slug: 'derazalar-balkonlar' },
      { id: 'cat_oboy_boyash', name_uz: "Oboylar va bo'yash ishlari", slug: 'oboylar-boyash-ishlari' },
      { id: 'cat_shiftlar', name_uz: 'Shiftlar', slug: 'shiftlar' },
      { id: 'cat_pol_qoplamalari', name_uz: 'Pollar va pol qoplamalari', slug: 'pollar-pol-qoplamalari' },
      { id: 'cat_suvoq_ishlari', name_uz: 'Suvoq ishlari', slug: 'suvoq-ishlari' },
      { id: 'cat_eshiklar', name_uz: 'Eshiklar', slug: 'eshiklar' },
      { id: 'cat_plitka_ishlari', name_uz: 'Plitka ishlari', slug: 'plitka-ishlari' },
      { id: 'cat_duradgorlik', name_uz: 'Duradgorlik va duradgorlik ishlari', slug: 'duradgorlik-ishlari' },
      { id: 'cat_gipsokarton', name_uz: 'Gipsokarton ishlari', slug: 'gipsokarton-ishlari' },
      { id: 'cat_balandlikdagi_ishlar', name_uz: 'Balandlikdagi ishlar', slug: 'balandlikdagi-ishlar' },
      { id: 'cat_izolyatsiya_isitish', name_uz: 'Izolyatsiya va isitish', slug: 'izolyatsiya-isitish' },
      { id: 'cat_tijorat_binolari', name_uz: "Tijorat binolarini ta'mirlash", slug: 'tijorat-binolarini-tamirlash' },
      { id: 'cat_ventilyatsiya', name_uz: 'Ventilyatsiya va konditsionerlash', slug: 'ventilyatsiya-konditsionerlash' },
      { id: 'cat_tamirlash_boshqa', name_uz: "Boshqa ta'mirlash ishlari", slug: 'boshqa-tamirlash' },
    ],
  },
  {
    id: 'cat_qurilish',
    name_uz: 'Qurilish',
    slug: 'qurilish',
    icon: 'Hammer',
    subs: [
      { id: 'cat_uylarni_tayyor_tamirlash', name_uz: "Uylarni tayyor holda ta'mirlash", slug: 'uylarni-tayyor-tamirlash' },
      { id: 'cat_garaj_hammom_veranda', name_uz: 'Garajlar, hammomlar, verandalar qurish', slug: 'garajlar-hammomlar-verandalar' },
      { id: 'cat_yogoch_uylar', name_uz: "Yog'och uylarni, hammomlarni, saunalarni tugatish", slug: 'yogoch-uylar-saunalar' },
      { id: 'cat_gisht_terish', name_uz: "G'isht terish ishlari", slug: 'gisht-terish-ishlari' },
      { id: 'cat_tom_yopish', name_uz: 'Tom yopish ishlari', slug: 'tom-yopish-ishlari' },
      { id: 'cat_payvandlash_metall', name_uz: 'Payvandlash, zarb qilish, metall konstruktsiyalar', slug: 'payvandlash-metall' },
      { id: 'cat_poydevor_beton', name_uz: 'Poydevor va beton ishlari', slug: 'poydevor-beton-ishlari' },
      { id: 'cat_olmos_burgulash', name_uz: "Olmosni burg'ulash va kesish", slug: 'olmosni-burgulash-kesish' },
      { id: 'cat_buzish_demontaj', name_uz: 'Buzish va demontaj ishlari', slug: 'buzish-demontaj-ishlari' },
      { id: 'cat_fasad_ishlari', name_uz: 'Fasad ishlari', slug: 'fasad-ishlari' },
      { id: 'cat_loyiha_smeta', name_uz: 'Loyiha va smeta', slug: 'loyiha-smeta' },
      { id: 'cat_umumiy_ishchilar', name_uz: 'Umumiy ishchilar', slug: 'umumiy-ishchilar' },
      { id: 'cat_sorov_ishi', name_uz: "So'rov ishi", slug: 'sorov-ishi' },
      { id: 'cat_zinalar', name_uz: 'Zinalar', slug: 'zinalar' },
      { id: 'cat_gazlashtirish', name_uz: 'Gazlashtirish', slug: 'gazlashtirish' },
      { id: 'cat_qurilish_boshqa', name_uz: 'Boshqa qurilish ishlari', slug: 'boshqa-qurilish' },
    ],
  },
  {
    id: 'cat_texnika',
    name_uz: "Texnikani ta'mirlash va xizmat",
    slug: 'texnikani-tamirlash',
    icon: 'Wrench',
    subs: [
      { id: 'cat_televizorlar', name_uz: 'Televizorlar', slug: 'televizorlar' },
      { id: 'cat_mobil_qurilmalar', name_uz: 'Mobil qurilmalar (Telefonlar, planshetlar)', slug: 'mobil-qurilmalar' },
      { id: 'cat_foto_audio_video', name_uz: 'Foto-, audio-, video uskunalar', slug: 'foto-audio-video' },
      { id: 'cat_konditsionerlar', name_uz: 'Konditsionerlar, ventilyatsiya', slug: 'konditsionerlar-ventilyatsiya' },
      { id: 'cat_kir_yuvish', name_uz: 'Kir yuvish va quritish mashinalari', slug: 'kir-yuvish-mashinalari' },
      { id: 'cat_idish_yuvish', name_uz: 'Idish yuvish mashinalari', slug: 'idish-yuvish-mashinalari' },
      { id: 'cat_sovutgichlar', name_uz: 'Sovutgichlar / holodilnik va muzlatgichlar', slug: 'sovutgichlar-muzlatgichlar' },
      { id: 'cat_plitalar_duxovkalar', name_uz: 'Pishirish panellari / plitalar va duxovkalar', slug: 'plitalar-va-duxovkalar' },
      { id: 'cat_gaz_qozonlari', name_uz: 'Gaz qozonlari, suv isitgichlari', slug: 'gaz-qozonlari-suv-isitgichlar' },
      { id: 'cat_kofe_mashinalari', name_uz: 'Kofe mashinalari', slug: 'kofe-mashinalari' },
      { id: 'cat_tikuv_mashinalari', name_uz: 'Tikuv mashinalari, overloklar', slug: 'tikuv-mashinalari' },
      { id: 'cat_elektr_ornatish', name_uz: "Elektr uskunalarini o'rnatish va montaj qilish", slug: 'elektr-uskunalar-ornatish' },
      { id: 'cat_sputnik_tv', name_uz: "Sputnik TV tuzatish va o'rnatish", slug: 'sputnik-tv-tuzatish' },
      { id: 'cat_texnika_boshqa', name_uz: "Boshqa maishiy texnika ta'miri", slug: 'boshqa-texnika' },
    ],
  },
  {
    id: 'cat_tozalash',
    name_uz: 'Tozalash (Klining)',
    slug: 'tozalash',
    icon: 'Sparkle',
    subs: [
      { id: 'cat_umumiy_tozalash', name_uz: 'Umumiy tozalash', slug: 'umumiy-tozalash' },
      { id: 'cat_dezinfektsiya', name_uz: 'Dezinfektsiya, dezinseksiya', slug: 'dezinfektsiya-dezinseksiya' },
      { id: 'cat_oyna_yuvish', name_uz: 'Oyna yuvish', slug: 'oyna-yuvish' },
      { id: 'cat_uy_tozalash', name_uz: 'Uy tozalash', slug: 'uy-tozalash' },
      { id: 'cat_tamirdan_keyin_tozalash', name_uz: "Ta'mirlashdan keyin tozalash", slug: 'tamirlashdan-keyin-tozalash' },
      { id: 'cat_gilam_yuvish', name_uz: 'Gilam yuvish', slug: 'gilam-yuvish' },
      { id: 'cat_yumshoq_mebel_yuvish', name_uz: 'Yumshoq mebel yuvish (Ximchistka)', slug: 'yumshoq-mebel-yuvish' },
    ],
  },
  {
    id: 'cat_bayramlar',
    name_uz: 'Bayramlar, tadbirlar',
    slug: 'bayramlar-tadbirlar',
    icon: 'PartyPopper',
    subs: [
      { id: 'cat_oshpazlik', name_uz: 'Oshpazlik & Restoran (Katering)', slug: 'oshpazlik-katering' },
      { id: 'cat_boshlovchi_dj', name_uz: 'Boshlovchi va DJ', slug: 'boshlovchi-dj' },
      { id: 'cat_foto_video_tadbirlar', name_uz: 'Foto va video suratga olish (Tadbirlar)', slug: 'foto-video-tadbirlar' },
      { id: 'cat_bezatish_dekor', name_uz: 'Bezatish va dekoratsiya', slug: 'bezatish-dekoratsiya' },
      { id: 'cat_musiqachilar', name_uz: 'Musiqachilar va jonli ijro', slug: 'musiqachilar-ijro' },
      { id: 'cat_bolalar_bayrami', name_uz: 'Bolalar bayramlari va animatorlar', slug: 'bolalar-bayramlari' },
      { id: 'cat_tadbirlar_boshqa', name_uz: 'Boshqa tadbir xizmatlari', slug: 'boshqa-tadbirlar' },
    ],
  },
  {
    id: 'cat_biznes',
    name_uz: 'Biznes xizmatlari',
    slug: 'biznes-xizmatlari',
    icon: 'Briefcase',
    subs: [
      { id: 'cat_savdo', name_uz: 'Savdo & Mijozlar bilan ishlash', slug: 'savdo-mijozlar' },
      { id: 'cat_buxgalteriya', name_uz: 'Buxgalteriya, moliya', slug: 'buxgalteriya-moliya' },
      { id: 'cat_konsalting', name_uz: 'Konsalting', slug: 'konsalting' },
      { id: 'cat_yuridik', name_uz: 'Yuridik xizmatlar', slug: 'yuridik-xizmatlar' },
      { id: 'cat_sugurta', name_uz: "Sug'urta", slug: 'sugurta' },
      { id: 'cat_biznes_boshqa', name_uz: 'Boshqa biznes xizmatlari', slug: 'boshqa-biznes' },
    ],
  },
  {
    id: 'cat_enagalar',
    name_uz: 'Enagalar, kasalga qarovchilar',
    slug: 'enagalar-qarovchilar',
    icon: 'HeartHandshake',
    subs: [
      { id: 'cat_enaga_bolalar', name_uz: 'Enaga (bolalar uchun)', slug: 'enaga-bolalar-uchun' },
      { id: 'cat_kasalga_qarovchi', name_uz: 'Kasalga qarovchi (patronaj)', slug: 'kasalga-qarovchi' },
      { id: 'cat_uy_bekasi', name_uz: 'Uy bekasi', slug: 'uy-bekasi' },
      { id: 'cat_qarovchilar_boshqa', name_uz: "Boshqa g'amxo'rlik xizmatlari", slug: 'boshqa-qarovchilar' },
    ],
  },
  {
    id: 'cat_uskunalar',
    name_uz: 'Uskunalar va ishlab chiqarish',
    slug: 'uskunalar-ishlab-chiqarish',
    icon: 'Cog',
    subs: [
      { id: 'cat_stanok_ijara', name_uz: 'Stanok va uskunalar ijarasi', slug: 'stanok-uskunalar-ijara' },
      { id: 'cat_metallga_ishlov', name_uz: 'Metallga ishlov berish', slug: 'metallga-ishlov-berish' },
      { id: 'cat_plastik_yogoch', name_uz: "Plastik va yog'och mahsulotlar", slug: 'plastik-yogoch-ishlab-chiqarish' },
      { id: 'cat_qadoqlash_uskunalari', name_uz: 'Qadoqlash uskunalari', slug: 'qadoqlash-uskunalari' },
      { id: 'cat_uskunalar_boshqa', name_uz: 'Boshqa ishlab chiqarish xizmatlari', slug: 'boshqa-uskunalar' },
    ],
  },
  {
    id: 'cat_kompyuter',
    name_uz: 'Kompyuter yordami',
    slug: 'kompyuter-yordami',
    icon: 'Laptop',
    subs: [
      { id: 'cat_kompyuterlar', name_uz: "Kompyuterlar (Noutbuk va PK ta'miri)", slug: 'kompyuterlar' },
      { id: 'cat_printerlar', name_uz: "Printerlar va kartrij to'ldirish", slug: 'printerlar' },
      { id: 'cat_mayning', name_uz: 'Mayning qurilmalari', slug: 'mayning' },
      { id: 'cat_oyin_konsollari', name_uz: "O'yin konsollari (PlayStation / Xbox)", slug: 'oyin-konsollari' },
      { id: 'cat_os_dasturlar', name_uz: "OS va dasturlar o'rnatish", slug: 'os-dasturlar' },
      { id: 'cat_internet_tarmoqlar', name_uz: 'Internet va mahalliy tarmoqlar (Wi-Fi, LAN)', slug: 'internet-tarmoqlar' },
      { id: 'cat_tamirlash_sozlash', name_uz: "Ta'mirlash va sozlash", slug: 'tamirlash-sozlash' },
    ],
  },
  {
    id: 'cat_chiqindi',
    name_uz: 'Chiqindilarni olib chiqish',
    slug: 'chiqindilarni-olib-chiqish',
    icon: 'Trash2',
    subs: [
      { id: 'cat_qurilish_chiqindilari', name_uz: 'Qurilish chiqindilari', slug: 'qurilish-chiqindilari' },
      { id: 'cat_maishiy_chiqindilar', name_uz: 'Maishiy chiqindilar', slug: 'maishiy-chiqindilar' },
      { id: 'cat_metallolom_xomashyo', name_uz: 'Metallolom va ikkilamchi xomashyo', slug: 'metallolom-xomashyo' },
      { id: 'cat_chiqindi_boshqa', name_uz: 'Boshqa utilizatsiya xizmatlari', slug: 'boshqa-chiqindi' },
    ],
  },
  {
    id: 'cat_talim',
    name_uz: 'Ta’lim, kurslar',
    slug: 'talim',
    icon: 'GraduationCap',
    subs: [
      { id: 'cat_maktab_universitet', name_uz: 'Maktab va universitet fanlari', slug: 'maktab-universitet-fanlari' },
      { id: 'cat_chet_tillari', name_uz: 'Chet tillari (Ingliz, Rus, Nemis, Arab, Xitoy)', slug: 'chet-tillari' },
      { id: 'cat_bolalar_rivojlanishi', name_uz: 'Bolalar rivojlanishi, logopedlar', slug: 'bolalar-rivojlanishi-logopedlar' },
      { id: 'cat_talim_it_biznes', name_uz: 'IT, biznes kurslari', slug: 'it-biznes-kurslari' },
      { id: 'cat_talim_dizayn', name_uz: 'Dizayn, chizmachilik', slug: 'dizayn-chizmachilik-kurslari' },
      { id: 'cat_talim_gozallik', name_uz: "Go'zallik, salomatlik kurslari", slug: 'gozallik-kurslari' },
      { id: 'cat_talim_sport', name_uz: "Sport, raqs to'garaklari", slug: 'sport-raqs-kurslari' },
      { id: 'cat_avtomaktab', name_uz: 'Haydovchilik, avtomaktab', slug: 'haydovchilik-avtomaktab' },
      { id: 'cat_musiqa_teatr', name_uz: 'Musiqa, teatr darslari', slug: 'musiqa-teatr-darslari' },
      { id: 'cat_kasbiy_talim', name_uz: "Kasbiy ta'lim", slug: 'kasbiy-talim' },
      { id: 'cat_talim_boshqa', name_uz: 'Boshqa repetitorlik va kurslar', slug: 'boshqa-talim' },
    ],
  },
  {
    id: 'cat_avto',
    name_uz: "Avtomobillarga xizmat ko'rsatish, ijara",
    slug: 'avto',
    icon: 'Car',
    subs: [
      { id: 'cat_avtoservis', name_uz: 'Avtoservis (Mator, xodovoy, moy almashtirish)', slug: 'avtoservis' },
      { id: 'cat_avto_ijara', name_uz: 'Avtomobil ijarasi (Rent car)', slug: 'avtomobil-ijarasi' },
      { id: 'cat_maxsus_texnika_ijarasi', name_uz: 'Maxsus texnika ijarasi (Kran, ekskavator)', slug: 'maxsus-texnika-ijarasi' },
      { id: 'cat_avto_diagnostika', name_uz: 'Kompyuter diagnostikasi va elektrik', slug: 'avto-diagnostika' },
      { id: 'cat_avto_boshqa', name_uz: 'Boshqa avto xizmatlari', slug: 'boshqa-avto' },
    ],
  },
  {
    id: 'cat_reklama',
    name_uz: 'Reklama, poligrafiya',
    slug: 'reklama-poligrafiya',
    icon: 'Megaphone',
    subs: [
      { id: 'cat_grafik_dizayner', name_uz: 'Grafik dizayner', slug: 'grafik-dizayner' },
      { id: 'cat_neon_belgisi', name_uz: 'Neon belgisi', slug: 'neon-belgisi' },
      { id: 'cat_vizitkalar', name_uz: 'Vizitkalar, taklifnomalar', slug: 'vizitkalar-taklifnomalar' },
      { id: 'cat_nakleykalar', name_uz: 'Nakleykalar, stikerlar', slug: 'nakleykalar-stikerlar' },
      { id: 'cat_logotip', name_uz: 'Logotip ishlab chiqish', slug: 'logotip-ishlab-chiqish' },
      { id: 'cat_viveskalar_bannerlar', name_uz: 'Viveskalar, bannerlar, reklama tayyorlash', slug: 'viveskalar-bannerlar' },
      { id: 'cat_futbolkalar_bosma', name_uz: 'Futbolkalarga bosma (Pechat)', slug: 'futbolkalarga-bosma' },
      { id: 'cat_bosmaxona', name_uz: 'Bosmaxona, tipografiya', slug: 'bosmaxona-tipografiya' },
      { id: 'cat_manzil_belgilari', name_uz: 'Manzil belgilari', slug: 'manzil-belgilari' },
      { id: 'cat_kiyim_teglar', name_uz: 'Kiyim uchun teglar', slug: 'kiyim-uchun-teglar' },
      { id: 'cat_tashqi_reklama', name_uz: 'Tashqi reklama (Bilbordlar)', slug: 'tashqi-reklama' },
      { id: 'cat_dizayn', name_uz: 'Dizayn xizmatlari', slug: 'dizayn-xizmatlari' },
      { id: 'cat_imzo_ornatish', name_uz: "Imzo o'rnatish", slug: 'imzo-ornatish' },
      { id: 'cat_magnitlar', name_uz: 'Magnitlar', slug: 'magnitlar' },
      { id: 'cat_reklama_ishlab_chiqarish', name_uz: 'Reklama ishlab chiqarish', slug: 'reklama-ishlab-chiqarish' },
      { id: 'cat_banner_chop', name_uz: 'Banner chop etish', slug: 'banner-chop-etish' },
      { id: 'cat_hujjatlar_foto', name_uz: 'Hujjatlar uchun fotosurat', slug: 'hujjatlar-uchun-fotosurat' },
    ],
  },
  {
    id: 'cat_it_dasturlash',
    name_uz: 'IT, marketing va media',
    slug: 'it-dasturlash',
    icon: 'Code',
    subs: [
      { id: 'cat_reklama_pr', name_uz: 'Reklama, PR, marketing', slug: 'reklama-pr-marketing' },
      { id: 'cat_dasturlash_crm', name_uz: 'Dasturlash, CRM sozlash', slug: 'dasturlash-crm-sozlash' },
      { id: 'cat_veb_ilovalar', name_uz: 'Veb-saytlar va ilovalar yaratish', slug: 'veb-saytlar-va-ilovalar' },
      { id: 'cat_matnlar_tarjimalar', name_uz: 'Matnlar, kopirayting', slug: 'matnlar-kopirayting' },
      { id: 'cat_marketpleyslar', name_uz: 'Marketpleyslar (Uzum, Wildberries)', slug: 'marketpleyslar-reklama' },
      { id: 'cat_smm_ijtimoiy', name_uz: 'Reklama, ijtimoiy tarmoqlar (SMM, Target)', slug: 'smm-ijtimoiy-tarmoqlar' },
      { id: 'cat_seo_kontekst', name_uz: 'SEO, kontekstli reklama (Google / Yandex)', slug: 'seo-kontekstli-reklama' },
      { id: 'cat_media', name_uz: 'OAV & Media xizmatlari', slug: 'media-xizmatlari' },
      { id: 'cat_it_boshqa', name_uz: 'Boshqa IT va marketing xizmatlari', slug: 'boshqa-it-marketing' },
    ],
  },
  {
    id: 'cat_transport',
    name_uz: 'Yuk tashish',
    slug: 'transport',
    icon: 'Truck',
    subs: [
      { id: 'cat_yuk_shahar_boylab', name_uz: 'Shahar bo‘ylab (Labo, Damas, Gazel)', slug: 'shahar-boylab-yuk-tashish' },
      { id: 'cat_yuk_shaharlar_aro', name_uz: "Shaharlar o'rtasida yuk tashish", slug: 'shaharlar-ortasida-yuk' },
      { id: 'cat_yuk_xalqaro', name_uz: 'Xalqaro yuk tashish (Fura, TIR)', slug: 'xalqaro-yuk-tashish' },
    ],
  },
  {
    id: 'cat_maishiy',
    name_uz: 'Maishiy xizmatlar',
    slug: 'maishiy-xizmatlar',
    icon: 'Home',
    subs: [
      { id: 'cat_kalit_yasash', name_uz: 'Kalit yasash va qulflar ochish', slug: 'kalit-yasash' },
      { id: 'cat_kiyim_tikish', name_uz: "Kiyimlarni tikish va ta'mirlash", slug: 'kiyimlarni-tikish-tamirlash' },
      { id: 'cat_soat_tamirlash', name_uz: "Soat ta'mirlash", slug: 'soat-tamirlash' },
      { id: 'cat_kimyoviy_tozalash', name_uz: 'Kimyoviy tozalash, yuvish', slug: 'kimyoviy-tozalash-yuvish' },
      { id: 'cat_foto_video_surat', name_uz: 'Foto va video suratga olish (Shaxsiy)', slug: 'foto-video-suratga-olish' },
      { id: 'cat_yetkazib_berish', name_uz: 'Oziq-ovqat va mahsulotlarni yetkazib berish (Kuryer)', slug: 'yetkazib-berish-kuryer' },
      { id: 'cat_hayvonlar_gamxorlik', name_uz: "Hayvonlarga g'amxo'rlik qilish (Gruming, vetvrach)", slug: 'hayvonlarga-gamxorlik' },
      { id: 'cat_bir_soatga_usta', name_uz: 'Bir soatga usta (Erkak kishi bir soatga)', slug: 'bir-soatga-usta' },
    ],
  },
  {
    id: 'cat_tarjimalar',
    name_uz: 'Tarjimalar',
    slug: 'tarjimalar',
    icon: 'Languages',
    subs: [
      { id: 'cat_tarjima_rus_uzb', name_uz: "Ruscha - o'zbekcha tarjimon", slug: 'ruscha-ozbekcha-tarjimon' },
      { id: 'cat_tarjima_uzb_rus', name_uz: "O'zbekcha - ruscha tarjimon", slug: 'ozbekcha-ruscha-tarjimon' },
      { id: 'cat_tarjima_ing_uzb', name_uz: "Inglizcha - o'zbekcha tarjimon", slug: 'inglizcha-ozbekcha-tarjimon' },
      { id: 'cat_tarjima_uzb_ing', name_uz: "O'zbekcha - inglizcha tarjimon", slug: 'ozbekcha-inglizcha-tarjimon' },
      { id: 'cat_tarjima_turk_rus', name_uz: 'Turk tilidan tarjimon', slug: 'turk-tili-tarjimon' },
      { id: 'cat_tarjima_xitoy', name_uz: 'Xitoy tili tarjimoni', slug: 'xitoy-tili-tarjimon' },
      { id: 'cat_tarjima_boshqa', name_uz: 'Boshqa tillar tarjimasi (Notarial tasdiqlash)', slug: 'boshqa-tarjimalar' },
    ],
  },
  {
    id: 'cat_bog',
    name_uz: "Bog', obodonlashtirish",
    slug: 'bog-obodonlashtirish',
    icon: 'Trees',
    subs: [
      { id: 'cat_quduqlar_septik', name_uz: 'Quduqlar, septik tanklar', slug: 'quduqlar-septik-tanklar' },
      { id: 'cat_hovuz_favvora', name_uz: 'Suv havzalari va favvoralar', slug: 'suv-havzalari-favvoralar' },
      { id: 'cat_yol_qurilishi', name_uz: "Yo'l qurilishi va asfaltlash", slug: 'yol-qurilishi' },
      { id: 'cat_tosiar_soyabonlar', name_uz: "To‘siqlar, soyabonlar, rolikli ustunlar", slug: 'tosiqlar-soyabonlar' },
      { id: 'cat_yer_qazish', name_uz: 'Yer qazish ishlari', slug: 'yer-qazish-ishlari' },
      { id: 'cat_kokalamzorlashtirish', name_uz: "Ko‘kalamzorlashtirish, bog‘ va polizni parvarish qilish", slug: 'kokalamzorlashtirish-bog' },
      { id: 'cat_bog_boshqa', name_uz: 'Boshqa obodonlashtirish ishlari', slug: 'boshqa-bog-ishlari' },
    ],
  },
  {
    id: 'cat_evakuator',
    name_uz: 'Evakuator xizmatlari',
    slug: 'evakuator-xizmatlari',
    icon: 'ShieldAlert',
    subs: [
      { id: 'cat_evakuator_yengil', name_uz: 'Yengil avtomobillar uchun evakuator', slug: 'yengil-evakuator' },
      { id: 'cat_evakuator_yuk', name_uz: 'Yuk avtomobillari uchun evakuator', slug: 'yuk-evakuator' },
      { id: 'cat_evakuator_texnika', name_uz: 'Maxsus texnika tashish evakuatori', slug: 'maxsus-texnika-evakuator' },
      { id: 'cat_evakuator_boshqa', name_uz: '24/7 Shaharlararo evakuator', slug: 'boshqa-evakuator' },
    ],
  },
  {
    id: 'cat_yuk_tashuvchilar',
    name_uz: 'Yuk tashuvchilar, ombor xizmatlari',
    slug: 'yuk-tashuvchilar-ombor',
    icon: 'Boxes',
    subs: [
      { id: 'cat_yuk_tashuvchi_odamlar', name_uz: 'Yuk tashuvchilar (Gruzchiklar)', slug: 'yuk-tashuvchilar-gruzchiklar' },
      { id: 'cat_tovarlarni_qadoqlash', name_uz: 'Tovarlarni qadoqlash', slug: 'tovarlarni-qadoqlash' },
      { id: 'cat_ombor_xizmatlari', name_uz: 'Ombor xizmatlari va saqlash', slug: 'ombor-xizmatlari' },
    ],
  },
  {
    id: 'cat_xavfsizlik',
    name_uz: "Qo'riqlash va xavfsizlik",
    slug: 'qoriqlash-xavfsizlik',
    icon: 'ShieldCheck',
    subs: [
      { id: 'cat_kuzatuv_kameralari', name_uz: "Kuzatuv kameralari o'rnatish (CCTV)", slug: 'kuzatuv-kameralari' },
      { id: 'cat_signalizatsiya_domofon', name_uz: 'Signalizatsiya va domofon montaji', slug: 'signalizatsiya-domofon' },
      { id: 'cat_qoriqchilar', name_uz: "Xavfsizlik xizmati (Qo'riqchilar)", slug: 'qoriqchilar-xizmati' },
      { id: 'cat_yongin_xavfsizligi', name_uz: "Yong'in xavfsizligi tizimlari", slug: 'yongin-xavfsizligi' },
    ],
  },
  {
    id: 'cat_yolovchi',
    name_uz: "Yo'lovchi tashish",
    slug: 'yolovchi-tashish',
    icon: 'Bus',
    subs: [
      { id: 'cat_transfer', name_uz: 'Transfer (Aeroport, vokzal kutib olish)', slug: 'transfer-aeroport' },
      { id: 'cat_avto_moto_buyurtma', name_uz: 'Avto-moto xizmatlar - buyurtma', slug: 'avto-moto-buyurtma' },
      { id: 'cat_shahar_aro_taksi', name_uz: 'Shaharlararo taksi', slug: 'shaharlararo-taksi' },
      { id: 'cat_mikroavtobus_ijara', name_uz: 'Mikroavtobus va avtobus ijarasi', slug: 'mikroavtobus-ijarasi' },
      { id: 'cat_yolovchi_boshqa', name_uz: "Boshqa yo'lovchi tashish xizmatlari", slug: 'boshqa-yolovchi-tashish' },
    ],
  },
  {
    id: 'cat_boshqa',
    catalog_id: 'services',
    name_uz: 'Boshqa xizmatlar',
    slug: 'boshqa',
    icon: 'MoreHorizontal',
    subs: [
      { id: 'cat_sanat_musiqa', name_uz: "San’at, musiqa va rassomlik", slug: 'sanat-va-musiqa' },
      { id: 'cat_universal_usta', name_uz: 'Universal usta xizmatlari', slug: 'universal-usta' },
      { id: 'cat_turli_xizmatlar', name_uz: 'Turli xil buyurtmalar va topshiriqlar', slug: 'turli-xizmatlar' },
    ],
  },
  // ─── Avito-aligned expansions (services) ────────────────────────────────
  {
    id: 'cat_sayohat',
    catalog_id: 'services',
    name_uz: 'Sayohat va turizm',
    slug: 'sayohat-turizm',
    icon: 'Plane',
    subs: [
      { id: 'cat_viza', name_uz: 'Viza rasmiylashtirish', slug: 'viza-rasmiylashtirish' },
      { id: 'cat_aviachipta', name_uz: "Aviachipta va temir yo'l chiptalari", slug: 'aviachipta' },
      { id: 'cat_tur_paketlar', name_uz: 'Tur paketlari (chet el, mahalliy)', slug: 'tur-paketlar' },
      { id: 'cat_mehmonxona_band', name_uz: 'Mehmonxonalar band qilish', slug: 'mehmonxona-band-qilish' },
      { id: 'cat_ekskursiya_gid', name_uz: 'Ekskursiya va gid xizmatlari', slug: 'ekskursiya-gid' },
      { id: 'cat_turistik_sugurta', name_uz: "Sayohat (turistik) sug'urtasi", slug: 'turistik-sugurta' },
      { id: 'cat_xalqaro_transfer', name_uz: 'Xalqaro transfer (aeroport, chegaralar)', slug: 'xalqaro-transfer' },
      { id: 'cat_sayohat_boshqa', name_uz: 'Boshqa turizm xizmatlari', slug: 'boshqa-sayohat' },
    ],
  },
  {
    id: 'cat_hayvonot',
    catalog_id: 'services',
    name_uz: 'Uy hayvonlari',
    slug: 'uy-hayvonlari',
    icon: 'PawPrint',
    subs: [
      { id: 'cat_vet_shifokor', name_uz: 'Veterinar shifokor (uyga kelish)', slug: 'veterinar-shifokor' },
      { id: 'cat_gruming', name_uz: 'Grooming va baknish', slug: 'gruming-baknish' },
      { id: 'cat_it_tarbiyalash', name_uz: 'It tarbiyalash (kinolog)', slug: 'it-tarbiyalash-kinolog' },
      { id: 'cat_hayvon_hotel', name_uz: 'Uy hayvonlari panjonasi (hotel)', slug: 'hayvonlar-panjonasi' },
      { id: 'cat_pitomnik', name_uz: 'Zotli hayvonlar (pitomnik, bolalash)', slug: 'pitomnik-zotli-hayvonlar' },
      { id: 'cat_vet_jarrohlik', name_uz: 'Veterinar jarrohligi va sterilizatsiya', slug: 'vet-jarrohlik' },
      { id: 'cat_hayvon_oziq', name_uz: 'Oziq-ovqat va aksessuarlar yetkazish', slug: 'hayvon-oziq-ovqat' },
      { id: 'cat_hayvon_boshqa', name_uz: 'Boshqa zootechxidmatlar', slug: 'boshqa-hayvonot' },
    ],
  },
  {
    id: 'cat_sport_dam_olish',
    catalog_id: 'services',
    name_uz: 'Sport, fitnes va dam olish',
    slug: 'sport-fitnes-dam-olish',
    icon: 'Dumbbell',
    subs: [
      { id: 'cat_personal_trainer', name_uz: 'Personal trener', slug: 'personal-trener' },
      { id: 'cat_yoga_pilates', name_uz: "Yo'ga, pilates, stretching", slug: 'yoga-pilates' },
      { id: 'cat_suzish', name_uz: 'Suzish havuzasi va trener', slug: 'suzish-havuzasi' },
      { id: 'cat_rahb_shoxob', name_uz: "Raqs studiyalari va to'garaklar", slug: 'raqs-studiyalari' },
      { id: 'cat_zal_sektsiya', name_uz: 'Sport zal va seksiyalar ijarasi', slug: 'sport-zal-seksiyalar' },
      { id: 'cat_turnir', name_uz: 'Turnirlar va musobaqalar tashkiliy ishlari', slug: 'turnirlar-musobaqalar' },
      { id: 'cat_eko_dam_olish', name_uz: "Ekologik dam olish (tovushqon, tog' sayohati)", slug: 'ekologik-dam-olish' },
      { id: 'cat_sport_boshqa', name_uz: 'Boshqa sport va dam olish xizmatlari', slug: 'boshqa-sport' },
    ],
  },
  {
    id: 'cat_studiya',
    catalog_id: 'services',
    name_uz: 'Studiya va kontent ishlab chiqarish',
    slug: 'studiya-kontent',
    icon: 'Camera',
    subs: [
      { id: 'cat_foto_studiya', name_uz: 'Foto studija ijarasi', slug: 'foto-studija-ijarasi' },
      { id: 'cat_video_studiya', name_uz: 'Video studiya, montaj va Color Grading', slug: 'video-studiya' },
      { id: 'cat_ovoz_yozish', name_uz: 'Ovoz yozish studiyasi, audio montaj', slug: 'ovoz-yozish-studiyasi' },
      { id: 'cat_product_photo', name_uz: 'Product photography (mahsulot suratga olish)', slug: 'product-photography' },
      { id: 'cat_podkast', name_uz: 'Podkast yozish va boshqarish', slug: 'podkast-yozish' },
      { id: 'cat_3d_animatsiya', name_uz: '3D modellashtirish va animatsiya', slug: '3d-animatsiya' },
      { id: 'cat_toy_video', name_uz: "To'y va tadbir video/foto ishlab chiqarish", slug: 'toy-video-foto' },
      { id: 'cat_studiya_boshqa', name_uz: 'Boshqa studiya xizmatlari', slug: 'boshqa-studiya' },
    ],
  },
  {
    id: 'cat_yuridik_notar',
    catalog_id: 'services',
    name_uz: 'Yuridik va notarial xizmatlar',
    slug: 'yuridik-notarial',
    icon: 'Scale',
    subs: [
      { id: 'cat_notarial', name_uz: 'Notarial tasdiq va davlat bojlari', slug: 'notarial-tasdiq' },
      { id: 'cat_apostil', name_uz: 'Apostil va legalizatsiya', slug: 'apostil-legalizatsiya' },
      { id: 'cat_advokat', name_uz: 'Advokat va huquqiy maslahat', slug: 'advokat-huquqiy-maslahat' },
      { id: 'cat_shell_register', name_uz: "MCHJ/UK register qilish, o'zgartirish", slug: 'shell-hudud-register' },
      { id: 'cat_litsenziya', name_uz: 'Litsenziya va ruxsatnomalar', slug: 'litsenziya-ruxsatnoma' },
      { id: 'cat_sud_ish', name_uz: 'Sud ish yurituvi (fuqaro, jinoyat, iqtisodiy)', slug: 'sud-ish-yurituvi' },
      { id: 'cat_irs_oila', name_uz: 'Irs va oilaviy huquq masalalari', slug: 'irs-oila-huquqi' },
      { id: 'cat_migratsiya_hujjat', name_uz: 'Migratsiya va yashash guvohnomasi', slug: 'migratsiya-yashash' },
      { id: 'cat_yuridik_boshqa', name_uz: 'Boshqa yuridik xizmatlar', slug: 'boshqa-yuridik' },
    ],
  },
  {
    id: 'cat_sugurta',
    catalog_id: 'services',
    name_uz: "Sug'urta xizmatlari",
    slug: 'sugurta-xizmatlari',
    icon: 'ShieldCheck',
    subs: [
      { id: 'cat_osago_kasko', name_uz: "Avto sug'urta (OSAGO, KASKO)", slug: 'avto-sugurta' },
      { id: 'cat_hayot_sugurta', name_uz: "Hayot va sog'lik sug'urtasi", slug: 'hayot-sugurta' },
      { id: 'cat_tibbiy_sugurta', name_uz: "Tibbiy sug'urta (DMV, xalqaro)", slug: 'tibbiy-sugurta' },
      { id: 'cat_mulk_sugurta', name_uz: "Ko'chmas mulk va uy sug'urtasi", slug: 'mulk-sugurta' },
      { id: 'cat_yur_yuk_sugurta', name_uz: "Yuk tashish sug'urtasi (kargo)", slug: 'yuk-sugurta' },
      { id: 'cat_biznes_sugurta', name_uz: "Biznes va javobgarlik sug'urtasi", slug: 'biznes-sugurta' },
      { id: 'cat_sugurta_boshqa', name_uz: "Boshqa sug'urta xizmatlari", slug: 'boshqa-sugurta' },
    ],
  },
  {
    id: 'cat_qurilish_material',
    catalog_id: 'services',
    name_uz: 'Qurilish materiallari va ehtiyot qismlar',
    slug: 'qurilish-materiallari',
    icon: 'Package',
    subs: [
      { id: 'cat_gisht_blok', name_uz: "G'isht, bloklar va beton mahsulotlar", slug: 'gisht-blok-beton' },
      { id: 'cat_sement_qum', name_uz: "Sement, qum, shag'al va aralashmalar", slug: 'sement-qum-shagal' },
      { id: 'cat_yogoch_laminat', name_uz: "Yog'och, laminat, parket va pol taxtasi", slug: 'yogoch-laminat' },
      { id: 'cat_profil_plitka', name_uz: 'Profil, gipsokarton, pletka va oluklar', slug: 'profil-gipsokarton' },
      { id: 'cat_elektro_material', name_uz: 'Elektr jihoz, kabl, rozetka va chiroqlar', slug: 'elektr-material' },
      { id: 'cat_boyoq_lak', name_uz: "Bo'yoq, lak, shpaklyovka va gruntovka", slug: 'boyoq-lak-shpaklyovka' },
      { id: 'cat_santeh_ehtiyot', name_uz: 'Santehnika ehtiyot qismlari va armatura', slug: 'santeh-ehtiyot-qismlar' },
      { id: 'cat_qur_material_boshqa', name_uz: 'Boshqa qurilish materiallari', slug: 'boshqa-qurilish-material' },
    ],
  },
  {
    id: 'cat_xalqaro_logistika',
    catalog_id: 'services',
    name_uz: 'Xalqaro xizmatlar va logistika',
    slug: 'xalqaro-xizmatlar-logistika',
    icon: 'Globe2',
    subs: [
      { id: 'cat_xalqaro_yetkazish', name_uz: 'Xalqaro yetkazib berish (pochta, kuryer)', slug: 'xalqaro-yetkazish' },
      { id: 'cat_bojxona', name_uz: 'Bojxona rasmiylashtiruvi', slug: 'bojxona-rasmiylashtirish' },
      { id: 'cat_migratsiya', name_uz: 'Migratsiya va ruxsatnoma xizmatlari', slug: 'migratsiya-xizmatlari' },
      { id: 'cat_viza_markaz', name_uz: 'Viza markaziga hujjat topshirish', slug: 'viza-markaz-hujjat' },
      { id: 'cat_chet_el_ish', name_uz: 'Chet elda ishga joylash', slug: 'chet-elda-ishga-joylash' },
      { id: 'cat_valyuta_otkazma', name_uz: "Valyuta o'tkazmalari va konsalting", slug: 'valyuta-otkazmalar' },
      { id: 'cat_xalqaro_boshqa', name_uz: 'Boshqa xalqaro xizmatlar', slug: 'boshqa-xalqaro' },
    ],
  },
  {
    id: 'cat_oziq_ovqat',
    catalog_id: 'services',
    name_uz: 'Oziq-ovqat va katering',
    slug: 'oziq-ovqat-katering',
    icon: 'Utensils',
    subs: [
      { id: 'cat_tayyor_ovqat_yetkaz', name_uz: 'Tayyor ovqat yetkazish (food delivery)', slug: 'tayyor-ovqat-yetkazish' },
      { id: 'cat_toyxona', name_uz: "To'yxona, katering va tantanali ovqat", slug: 'toyxona-katering' },
      { id: 'cat_farmon_asal', name_uz: 'Farmon, asal va sut mahsulotlari', slug: 'farmon-asal-sut' },
      { id: 'cat_un_guruch', name_uz: 'Un, shakar, guruch va don mahsulotlari (ulgurji)', slug: 'un-guruch-don' },
      { id: 'cat_konserva_quritilgan', name_uz: "Konserva, quritilgan meva va yong'oq mahsulotlari", slug: 'konserva-quritilgan-meva' },
      { id: 'cat_ichimlik_suv', name_uz: 'Ichimliklar va suv yetkazib berish', slug: 'ichimlik-suv' },
      { id: 'cat_shirinlik_tort', name_uz: 'Tort, shirinlik va konfetlar', slug: 'tort-shirinlik' },
      { id: 'cat_oziq_boshqa', name_uz: 'Boshqa oziq-ovqat xizmatlari', slug: 'boshqa-oziq-ovqat' },
    ],
  },
];

export const JOBS_CATALOG: ParentCategorySpec[] = [
  {
    id: 'cat_job_savdo',
    catalog_id: 'jobs',
    name_uz: 'Savdo va mijozlarga xizmat',
    slug: 'ish-savdo-va-mijozlarga-xizmat',
    icon: 'ShoppingBag',
    subs: [
      { id: 'cat_job_sotuvchi', name_uz: 'Sotuvchi-konsultant', slug: 'ish-sotuvchi-konsultant' },
      { id: 'cat_job_kassir', name_uz: 'Kassir', slug: 'ish-kassir' },
      { id: 'cat_job_savdo_vakili', name_uz: 'Savdo vakili / Agent', slug: 'ish-savdo-vakili' },
      { id: 'cat_job_merchendayzer', name_uz: 'Merchendayzer', slug: 'ish-merchendayzer' },
      { id: 'cat_job_dokon_mudiri', name_uz: 'Do‘kon boshqaruvchisi / Administrator', slug: 'ish-dokon-boshqaruvchisi' },
    ],
  },
  {
    id: 'cat_job_it',
    catalog_id: 'jobs',
    name_uz: 'IT, dasturlash va texnologiyalar',
    slug: 'ish-it-dasturlash-texnologiyalar',
    icon: 'Laptop',
    subs: [
      { id: 'cat_job_dasturchi', name_uz: 'Dasturchi (Frontend, Backend, Mobile)', slug: 'ish-dasturchi' },
      { id: 'cat_job_dizayner', name_uz: 'Veb / Grafika va UI/UX dizayner', slug: 'ish-veb-dizayner' },
      { id: 'cat_job_smm', name_uz: 'SMM va target mutaxassisi', slug: 'ish-smm-target' },
      { id: 'cat_job_tizim_admin', name_uz: 'Tizim ma’muri va Helpdesk', slug: 'ish-tizim-mamuri' },
      { id: 'cat_job_qa', name_uz: 'QA / Testlovchi mutaxassis', slug: 'ish-qa-tester' },
    ],
  },
  {
    id: 'cat_job_restoran',
    catalog_id: 'jobs',
    name_uz: 'Restoran, kafelar va umumiy ovqatlanish',
    slug: 'ish-restoran-kafelar',
    icon: 'Coffee',
    subs: [
      { id: 'cat_job_oshpaz', name_uz: 'Oshpaz va oshpaz yordamchisi', slug: 'ish-oshpaz' },
      { id: 'cat_job_ofitsiant', name_uz: 'Ofitsiant', slug: 'ish-ofitsiant' },
      { id: 'cat_job_barista', name_uz: 'Barista va barmen', slug: 'ish-barista-barmen' },
      { id: 'cat_job_fastfud', name_uz: 'Fast-fud ustasi / Pitsameker', slug: 'ish-fast-fud-ustasi' },
      { id: 'cat_job_oshxona_ishchi', name_uz: 'Idish yuvuvchi va oshxona yordamchisi', slug: 'ish-idish-yuvuvchi' },
    ],
  },
  {
    id: 'cat_job_logistika',
    catalog_id: 'jobs',
    name_uz: 'Haydovchilik, yetkazib berish va logistika',
    slug: 'ish-haydovchilik-yetkazib-berish',
    icon: 'Truck',
    subs: [
      { id: 'cat_job_kuryer', name_uz: 'Kuryer (piyoda, skuter, avto)', slug: 'ish-kuryer' },
      { id: 'cat_job_haydovchi', name_uz: 'Haydovchi (B, C, D toifa)', slug: 'ish-haydovchi' },
      { id: 'cat_job_omborchi', name_uz: 'Omborchi va hisobchi', slug: 'ish-omborchi' },
      { id: 'cat_job_gruzchik', name_uz: 'Yuk ortuvchi (gruzchik)', slug: 'ish-yuk-ortuvchi' },
      { id: 'cat_job_dispetcher', name_uz: 'Logistika dispetcheri', slug: 'ish-logistika-dispetcheri' },
    ],
  },
  {
    id: 'cat_job_ishlab_chiqarish',
    catalog_id: 'jobs',
    name_uz: 'Ishlab chiqarish, sex va fabrikalar',
    slug: 'ish-ishlab-chiqarish-sexlar',
    icon: 'Factory',
    subs: [
      { id: 'cat_job_tikuvchi', name_uz: 'Tikuvchi, bichuvchi, dazmolchi', slug: 'ish-tikuvchi' },
      { id: 'cat_job_operator', name_uz: 'Dastgoh operatori', slug: 'ish-dastgoh-operatori' },
      { id: 'cat_job_qadoqlovchi', name_uz: 'Qadoqlovchi va saralovchi', slug: 'ish-qadoqlovchi' },
      { id: 'cat_job_usta_brigada', name_uz: 'Sex ustasi / Brigadir', slug: 'ish-sex-ustasi' },
      { id: 'cat_job_oddiy_ishchi', name_uz: 'Sex ishchisi', slug: 'ish-sex-ishchisi' },
    ],
  },
  {
    id: 'cat_job_qurilish',
    catalog_id: 'jobs',
    name_uz: 'Qurilish va ta’mirlash ustalari',
    slug: 'ish-qurilish-tamirlash-ustalari',
    icon: 'Hammer',
    subs: [
      { id: 'cat_job_santexnik', name_uz: 'Santexnik', slug: 'ish-santexnik' },
      { id: 'cat_job_elektrchi', name_uz: 'Elektrik', slug: 'ish-elektrik' },
      { id: 'cat_job_suvoqchi', name_uz: 'Suvoqchi / Bo‘yoqchi / Molyar', slug: 'ish-suvoqchi-boyoqchi' },
      { id: 'cat_job_svarchik', name_uz: 'Payvandchi (svarchik)', slug: 'ish-payvandchi' },
      { id: 'cat_job_plitkachi', name_uz: 'Plitka ustasi', slug: 'ish-plitka-ustasi' },
      { id: 'cat_job_duradgor', name_uz: 'Duradgor va mebelchi', slug: 'ish-duradgor-mebelchi' },
    ],
  },
  {
    id: 'cat_job_ofis',
    catalog_id: 'jobs',
    name_uz: 'Ofis, ma’muriyat va kantselyariya',
    slug: 'ish-ofis-mamuriyat',
    icon: 'Building2',
    subs: [
      { id: 'cat_job_administrator', name_uz: 'Administrator va reception', slug: 'ish-administrator' },
      { id: 'cat_job_call_center', name_uz: 'Call-markaz operatori', slug: 'ish-call-markaz-operatori' },
      { id: 'cat_job_hr', name_uz: 'HR va kadrlar menejeri', slug: 'ish-hr-kadrlar' },
      { id: 'cat_job_kotiba', name_uz: 'Kotib / Ofis menejeri', slug: 'ish-kotib-ofis-menejeri' },
    ],
  },
  {
    id: 'cat_job_moliya',
    catalog_id: 'jobs',
    name_uz: 'Buxgalteriya, audit va moliya',
    slug: 'ish-buxgalteriya-moliya',
    icon: 'Calculator',
    subs: [
      { id: 'cat_job_bosh_buxgalter', name_uz: 'Bosh buxgalter', slug: 'ish-bosh-buxgalter' },
      { id: 'cat_job_buxgalter_yordamchi', name_uz: 'Buxgalter yordamchisi', slug: 'ish-buxgalter-yordamchisi' },
      { id: 'cat_job_iqtisodchi', name_uz: 'Iqtisodchi / Moliyachi', slug: 'ish-iqtisodchi' },
      { id: 'cat_job_auditor', name_uz: 'Auditor va soliq maslahatchisi', slug: 'ish-auditor' },
    ],
  },
  {
    id: 'cat_job_talim',
    catalog_id: 'jobs',
    name_uz: 'Ta’lim, repetitorlik va tarbiya',
    slug: 'ish-talim-repetitorlik',
    icon: 'GraduationCap',
    subs: [
      { id: 'cat_job_oqituvchi', name_uz: 'O‘qituvchi va murabbiy', slug: 'ish-oqituvchi' },
      { id: 'cat_job_repetitor', name_uz: 'Repetitor (fanlar / tillar)', slug: 'ish-repetitor' },
      { id: 'cat_job_tarbiyachi', name_uz: 'Bog‘cha tarbiyachisi', slug: 'ish-tarbiyachi' },
      { id: 'cat_job_instruktor', name_uz: 'Sport yoki haydovchilik instruktori', slug: 'ish-instruktor' },
    ],
  },
  {
    id: 'cat_job_tibbiyot',
    catalog_id: 'jobs',
    name_uz: 'Tibbiyot va farmatsevtika',
    slug: 'ish-tibbiyot-farmatsevtika',
    icon: 'Activity',
    subs: [
      { id: 'cat_job_shifokor', name_uz: 'Shifokor (turli sohalar)', slug: 'ish-shifokor' },
      { id: 'cat_job_hamshira', name_uz: 'Hamshira / Feldsher', slug: 'ish-hamshira' },
      { id: 'cat_job_farmatsevt', name_uz: 'Farmatsevt / Provizor', slug: 'ish-farmatsevt' },
      { id: 'cat_job_stomatolog', name_uz: 'Stomatolog va assistent', slug: 'ish-stomatolog' },
    ],
  },
  {
    id: 'cat_job_xizmat_xodimlari',
    catalog_id: 'jobs',
    name_uz: 'Xavfsizlik va xo‘jalik xizmati',
    slug: 'ish-xavfsizlik-va-xojalik',
    icon: 'ShieldCheck',
    subs: [
      { id: 'cat_job_qorovul', name_uz: 'Qorovul / Qo‘riqchi', slug: 'ish-qorovul' },
      { id: 'cat_job_farrosh', name_uz: 'Farrosh / Tozalik xodimi', slug: 'ish-farrosh' },
      { id: 'cat_job_bogbon', name_uz: 'Bog‘bon va gulchi', slug: 'ish-bogbon' },
    ],
  },
  {
    id: 'cat_job_talabalar',
    catalog_id: 'jobs',
    name_uz: 'Talabalar, boshlang‘ich va kunlik ishlar',
    slug: 'ish-talabalar-boshlangich-ishlar',
    icon: 'Sparkles',
    subs: [
      { id: 'cat_job_kunlik', name_uz: 'Kunlik ishlar (kunbay to‘lov)', slug: 'ish-kunlik-ishlar' },
      { id: 'cat_job_promo', name_uz: 'Promo-aksiyachi / Flayer tarqatuvchi', slug: 'ish-promo-flayer' },
      { id: 'cat_job_masofaviy', name_uz: 'Masofaviy ish / Frilans', slug: 'ish-masofaviy-frilans' },
      { id: 'cat_job_stajyor', name_uz: 'Stajyor / O‘rganuvchi', slug: 'ish-stajyor' },
    ],
  },
  // ─── Avito-aligned expansions (jobs) ───────────────────────────────────────
  {
    id: 'cat_job_marketing',
    catalog_id: 'jobs',
    name_uz: 'Marketing, reklama va PR',
    slug: 'ish-marketing-reklama-pr',
    icon: 'Megaphone',
    subs: [
      { id: 'cat_job_marketolog', name_uz: 'Marketolog / Brand menejeri', slug: 'ish-marketolog' },
      { id: 'cat_job_smm_manager', name_uz: 'SMM menejer va kontent-menejer', slug: 'ish-smm-menejer' },
      { id: 'cat_job_target_reklama', name_uz: 'Target va kontekstli reklama mutaxassisi', slug: 'ish-target-reklama' },
      { id: 'cat_job_seo_specialist', name_uz: 'SEO mutaxassisi', slug: 'ish-seo-specialist' },
      { id: 'cat_job_pr_holding', name_uz: "PR menejer va media-bog'liq", slug: 'ish-pr-menejer' },
      { id: 'cat_job_biznes_dizayner', name_uz: 'Grafik, UI/UX va motion dizayner', slug: 'ish-grafik-dizayner' },
      { id: 'cat_job_kopirayter', name_uz: 'Kopirayter, kontent-muallif, editor', slug: 'ish-kopirayter' },
      { id: 'cat_job_marketolog_boshqa', name_uz: 'Boshqa marketing va reklama lavozimlari', slug: 'ish-boshqa-marketing' },
    ],
  },
  {
    id: 'cat_job_davlat',
    catalog_id: 'jobs',
    name_uz: 'Davlat xizmati va harbiy ish',
    slug: 'ish-davlat-xizmati-harbiy',
    icon: 'Landmark',
    subs: [
      { id: 'cat_job_davlat_xizmatchi', name_uz: 'Davlat xizmatchisi (mahalla, hokimlik)', slug: 'ish-davlat-xizmatchi' },
      { id: 'cat_job_byurokratik', name_uz: 'Vedomstvo va idoralar xodimi', slug: 'ish-idoralar-xodimi' },
      { id: 'cat_job_politsiya', name_uz: 'Ichki ishlar, xavfsizlik xizmati', slug: 'ish-ichki-ishlar' },
      { id: 'cat_job_harbiy', name_uz: 'Harbiy xizmat va kontrakt', slug: 'ish-harbiy-xizmat' },
      { id: 'cat_job_sogiqka', name_uz: 'Bojxona, soliq va monitoring', slug: 'ish-bojxona-soliq' },
      { id: 'cat_job_tibbiy_davlat', name_uz: 'Davlat shifoxonalari va poliklinikalari', slug: 'ish-davlat-shifoxonasi' },
      { id: 'cat_job_davlat_boshqa', name_uz: 'Boshqa davlat va byudjet tashkilotlari', slug: 'ish-boshqa-davlat' },
    ],
  },
  {
    id: 'cat_job_bank_moliya',
    catalog_id: 'jobs',
    name_uz: "Bank, moliya va sug'urta",
    slug: 'ish-bank-moliya-sugurta',
    icon: 'Landmark',
    subs: [
      { id: 'cat_job_bank_operator', name_uz: 'Bank operatori va kassiri', slug: 'ish-bank-operatori' },
      { id: 'cat_job_kredit_menejer', name_uz: 'Kredit menejeri', slug: 'ish-kredit-menejer' },
      { id: 'cat_job_moliyaviy_tahlilchi', name_uz: 'Moliyaviy tahlilchi va investor', slug: 'ish-moliya-tahlilchi' },
      { id: 'cat_job_valyuta_ayirbosh', name_uz: 'Valyuta-ayirboshlash punkti xodimi', slug: 'ish-valyuta-ayirboshlash' },
      { id: 'cat_job_sugurta_agent', name_uz: "Sug'urta agenti va eksperti", slug: 'ish-sugurta-agenti' },
      { id: 'cat_job_anti_kochir', name_uz: 'Anti-fitna, AML va komplayens', slug: 'ish-aml-komplayens' },
      { id: 'cat_bank_boshqa', name_uz: 'Boshqa bank-moliya lavozimlari', slug: 'ish-boshqa-bank' },
    ],
  },
  {
    id: 'cat_job_top_menejer',
    catalog_id: 'jobs',
    name_uz: "Yuqori bo'g'in rahbariyati (Top-menejer)",
    slug: 'ish-top-menejer',
    icon: 'Crown',
    subs: [
      { id: 'cat_job_ceo', name_uz: 'ICX / Bosh direktor (CEO)', slug: 'ish-bosh-direktor' },
      { id: 'cat_job_cfo', name_uz: 'Moliya direktori (CFO)', slug: 'ish-moliya-direktori' },
      { id: 'cat_job_cto', name_uz: 'Texnologiya direktori (CTO)', slug: 'ish-cto' },
      { id: 'cat_job_cmo', name_uz: 'Marketing direktori (CMO)', slug: 'ish-cmo' },
      { id: 'cat_job_hr_director', name_uz: 'HR direktori', slug: 'ish-hr-direktori' },
      { id: 'cat_job_operatsion', name_uz: 'Operatsion va logistika direktori (COO)', slug: 'ish-coo' },
      { id: 'cat_job_bosh_menejer_boshqa', name_uz: 'Boshqa top-menejer lavozimlari', slug: 'ish-boshqa-top-menejer' },
    ],
  },
  {
    id: 'cat_job_sanat_oav',
    catalog_id: 'jobs',
    name_uz: "San'at, ko'ngilochar va OAV",
    slug: 'ish-sanat-kongilochar-oav',
    icon: 'Music',
    subs: [
      { id: 'cat_job_aktor', name_uz: "Aktyor, aktrisa va model", slug: 'ish-aktor-model' },
      { id: 'cat_job_musiqachi', name_uz: "Musiqachi, qo'shiqchi va DJ", slug: 'ish-musiqachi' },
      { id: 'cat_job_rejissyor', name_uz: 'Rejissyor, ssenarist va prodyuser', slug: 'ish-rejissyor' },
      { id: 'cat_job_jurnalist', name_uz: 'Jurnalist, muhbir va boshlovchi', slug: 'ish-jurnalist' },
      { id: 'cat_job_operator', name_uz: 'Operator, montajchi va Colorist', slug: 'ish-operator-montajchi' },
      { id: 'cat_job_animatsiya', name_uz: 'Animator, 3D va VFX artist', slug: 'ish-animator-3d' },
      { id: 'cat_job_tadbir_tashkilotchi', name_uz: 'Tadbir tashkilotchi (Event menejer)', slug: 'ish-event-menejer' },
      { id: 'cat_job_sanat_boshqa', name_uz: "Boshqa san'at va OAV lavozimlari", slug: 'ish-boshqa-sanat' },
    ],
  },
  {
    id: 'cat_job_mehmonxona',
    catalog_id: 'jobs',
    name_uz: 'Mehmonxona, turizm va ovqatlanish',
    slug: 'ish-mehmonxona-turizm',
    icon: 'Hotel',
    subs: [
      { id: 'cat_job_mehmonxona_admin', name_uz: 'Mehmonxona administratori (Reseption)', slug: 'ish-mehmonxona-administrator' },
      { id: 'cat_job_ofitsiant_xizm', name_uz: 'Ofitsiant, metrdotel va barmen', slug: 'ish-ofitsiant-metrdotel' },
      { id: 'cat_job_oshpaz_oav', name_uz: 'Oshpaz, konditer va suši mastersi', slug: 'ish-oshpaz-konditer' },
      { id: 'cat_job_gid', name_uz: 'Tarjimon gid va ekskursovod', slug: 'ish-gid-ekskursovod' },
      { id: 'cat_job_travel_menejer', name_uz: 'Travel-agent va tur menejeri', slug: 'ish-travel-menejer' },
      { id: 'cat_job_xojalik', name_uz: 'Xojalik xizmati va gorichiy', slug: 'ish-xojalik-xizmati' },
      { id: 'cat_job_mehmonxona_boshqa', name_uz: 'Boshqa mehmonxona va turizm lavozimlari', slug: 'ish-boshqa-mehmonxona' },
    ],
  },
  {
    id: 'cat_job_oddish_ishchi',
    catalog_id: 'jobs',
    name_uz: 'Oddiy ishchi kuchi (Blue-collar)',
    slug: 'ish-oddish-ishchi-kuchi',
    icon: 'HardHat',
    subs: [
      { id: 'cat_job_qurilish_ishchi', name_uz: 'Qurilish ishchilari (podrabotchik)', slug: 'ish-qurilish-ishchilari' },
      { id: 'cat_job_yuk_tashuvchi', name_uz: "Gruzeik va yuk ko'taruvchi", slug: 'ish-gruzchik' },
      { id: 'cat_job_tozalash_ishchi', name_uz: 'Tozalash va kliring ishchisi', slug: 'ish-tozalash-ishchisi' },
      { id: 'cat_job_fabrishniy', name_uz: 'Fabrika va sex ishchilari', slug: 'ish-fabrika-ishchilari' },
      { id: 'cat_job_qurilish_usta', name_uz: 'Podrabotchik, gazovshchik, svarchik va boshqalar', slug: 'ish-qurilish-ustasi' },
      { id: 'cat_job_tikuvchik', name_uz: 'Tikuvchi, bichuvchi, zhariga ishchi', slug: 'ish-tikuvchi-ayollar' },
      { id: 'cat_job_oddish_boshqa', name_uz: 'Boshqa oddiy ishchi kuchi', slug: 'ish-boshqa-oddish-ishchi' },
    ],
  },
  {
    id: 'cat_job_uy_xizmati',
    catalog_id: 'jobs',
    name_uz: 'Uy xizmati va shaxsiy yordamchi',
    slug: 'ish-uy-xizmati',
    icon: 'Home',
    subs: [
      { id: 'cat_job_ayoli', name_uz: 'Uy bekasi (domrabochaya)', slug: 'ish-uy-bekasi' },
      { id: 'cat_job_enaga_ish', name_uz: 'Enaga (nanny) va ayol-hamshira', slug: 'ish-enaga-hamshira' },
      { id: 'cat_job_qarash_keksalar', name_uz: 'Keksalar parvarishi (sidelka)', slug: 'ish-sidelka' },
      { id: 'cat_job_shoxoy_ish', name_uz: 'Shofyor va personal haydovchi', slug: 'ish-shofyor' },
      { id: 'cat_job_qorovuli', name_uz: 'Uy qorovuli va xavfsizlik xodimi', slug: 'ish-uy-qorovuli' },
      { id: 'cat_job_bogbon_ish', name_uz: "Bog'bbon va uy bekori", slug: 'ish-bogbbon' },
      { id: 'cat_job_uy_boshqa', name_uz: 'Boshqa uy xizmati lavozimlari', slug: 'ish-boshqa-uy-xizmati' },
    ],
  },
  {
    id: 'cat_job_sport',
    catalog_id: 'jobs',
    name_uz: 'Sport, fitnes va salomatlik',
    slug: 'ish-sport-fitnes',
    icon: 'Dumbbell',
    subs: [
      { id: 'cat_job_trener', name_uz: 'Fitnes trener va personal trener', slug: 'ish-fitnes-trener' },
      { id: 'cat_job_sport_instruktor', name_uz: 'Sport maktablari instruktorlari', slug: 'ish-sport-instruktor' },
      { id: 'cat_job_yoga_raqs', name_uz: 'Yo‘ga, pilates va raqs instruktori', slug: 'ish-yoga-raqs-instruktor' },
      { id: 'cat_job_murabbiy', name_uz: 'Murabbiy va jamoa treneri', slug: 'ish-murabbiy' },
      { id: 'cat_job_reabilitolog', name_uz: 'Reabilitolog va massajchi', slug: 'ish-reabilitolog' },
      { id: 'cat_job_nutriyolog', name_uz: 'Nutriyolog va parhezshunos', slug: 'ish-nutriyolog' },
      { id: 'cat_job_sport_boshqa', name_uz: 'Boshqa sport va fitnes lavozimlari', slug: 'ish-boshqa-sport' },
    ],
  },
  {
    id: 'cat_job_yurist',
    catalog_id: 'jobs',
    name_uz: 'Yurist va huquqshunoslar',
    slug: 'ish-yuristlar',
    icon: 'Scale',
    subs: [
      { id: 'cat_job_yurist_korxona', name_uz: 'Korxona yuristi (in-house)', slug: 'ish-korxona-yuristi' },
      { id: 'cat_job_advokat_ish', name_uz: 'Advokat va sud vakili', slug: 'ish-advokat' },
      { id: 'cat_job_notarial_ish', name_uz: 'Notarial xodimi va yordamchisi', slug: 'ish-notarial-xodimi' },
      { id: 'cat_job_soliq_yurist', name_uz: 'Soliq va bojxona yuristi', slug: 'ish-soliq-yurist' },
      { id: 'cat_job_huquqshunos', name_uz: 'Huquqshunos-tahlilchi va ilmiy xodim', slug: 'ish-huquqshunos' },
      { id: 'cat_job_sudya', name_uz: 'Sudya va sud jarayonchilari', slug: 'ish-sudya-kategoriya' },
      { id: 'cat_job_yurist_boshqa', name_uz: 'Boshqa yuridik lavozimlar', slug: 'ish-boshqa-yurist' },
    ],
  },
];

export const ALL_CATALOG_CATEGORIES: ParentCategorySpec[] = [
  ...CATEGORIES_CATALOG.map((c) => ({ ...c, catalog_id: c.catalog_id || 'services' })),
  ...JOBS_CATALOG,
];
