export interface DistrictData {
  id: string;
  region_id: string;
  name_uz: string;
  lat: number;
  lon: number;
  order: number;
}

export const UZBEKISTAN_DISTRICTS: DistrictData[] = [
  // ─── Toshkent shahri (12 tuman) ──────────────────────────────────────
  { id: 'dis_yunusobod',      region_id: 'reg_toshkent_sh', name_uz: 'Yunusobod tumani',          lat: 41.3650, lon: 69.2900, order: 1 },
  { id: 'dis_mirzo_ulugbek',  region_id: 'reg_toshkent_sh', name_uz: "Mirzo Ulug'bek tumani",     lat: 41.3300, lon: 69.3400, order: 2 },
  { id: 'dis_chilonzor',      region_id: 'reg_toshkent_sh', name_uz: 'Chilonzor tumani',          lat: 41.2750, lon: 69.2050, order: 3 },
  { id: 'dis_yakkasaroy',     region_id: 'reg_toshkent_sh', name_uz: 'Yakkasaroy tumani',         lat: 41.2850, lon: 69.2550, order: 4 },
  { id: 'dis_shayxontohur',   region_id: 'reg_toshkent_sh', name_uz: 'Shayxontohur tumani',       lat: 41.3200, lon: 69.2450, order: 5 },
  { id: 'dis_olmazor',        region_id: 'reg_toshkent_sh', name_uz: 'Olmazor tumani',            lat: 41.3450, lon: 69.2150, order: 6 },
  { id: 'dis_uchtepa',        region_id: 'reg_toshkent_sh', name_uz: 'Uchtepa tumani',            lat: 41.2950, lon: 69.1750, order: 7 },
  { id: 'dis_bektemir',       region_id: 'reg_toshkent_sh', name_uz: 'Bektemir tumani',           lat: 41.2200, lon: 69.3450, order: 8 },
  { id: 'dis_mirobod',        region_id: 'reg_toshkent_sh', name_uz: 'Mirobod tumani',            lat: 41.2950, lon: 69.2850, order: 9 },
  { id: 'dis_sirg_ali',       region_id: 'reg_toshkent_sh', name_uz: 'Sergeli tumani',            lat: 41.2250, lon: 69.2250, order: 10 },
  { id: 'dis_yashnobod',      region_id: 'reg_toshkent_sh', name_uz: 'Yashnobod tumani',          lat: 41.2950, lon: 69.3350, order: 11 },
  { id: 'dis_yangihayot',     region_id: 'reg_toshkent_sh', name_uz: 'Yangihayot tumani',         lat: 41.2050, lon: 69.2150, order: 12 },

  // ─── Toshkent viloyati (14 tuman + shaharlar) ─────────────────────────
  { id: 'dis_chirchiq',         region_id: 'reg_toshkent', name_uz: 'Chirchiq shahri',              lat: 41.4689, lon: 69.5822, order: 1 },
  { id: 'dis_angren',           region_id: 'reg_toshkent', name_uz: 'Angren shahri',               lat: 41.0167, lon: 70.1436, order: 2 },
  { id: 'dis_olmaliq',          region_id: 'reg_toshkent', name_uz: 'Olmaliq shahri',              lat: 40.8500, lon: 69.6000, order: 3 },
  { id: 'dis_bekobod_sh',       region_id: 'reg_toshkent', name_uz: 'Bekobod shahri',              lat: 40.2167, lon: 69.2167, order: 4 },
  { id: 'dis_yangiyol_sh',      region_id: 'reg_toshkent', name_uz: "Yangiyo'l shahri",            lat: 41.1167, lon: 69.0500, order: 5 },
  { id: 'dis_bostonliq',        region_id: 'reg_toshkent', name_uz: "Bo'stonliq tumani",           lat: 41.5667, lon: 69.7667, order: 6 },
  { id: 'dis_qibray',           region_id: 'reg_toshkent', name_uz: 'Qibray tumani',               lat: 41.3833, lon: 69.4500, order: 7 },
  { id: 'dis_zangiota',         region_id: 'reg_toshkent', name_uz: 'Zangiota tumani',             lat: 41.2333, lon: 69.1500, order: 8 },
  { id: 'dis_parkent',          region_id: 'reg_toshkent', name_uz: 'Parkent tumani',              lat: 41.2944, lon: 69.6764, order: 9 },
  { id: 'dis_yuqorichirchiq',   region_id: 'reg_toshkent', name_uz: 'Yuqori Chirchiq tumani',      lat: 41.2833, lon: 69.5333, order: 10 },
  { id: 'dis_ortepa',           region_id: 'reg_toshkent', name_uz: 'Ortachirchiq tumani',         lat: 41.2000, lon: 69.4333, order: 11 },
  { id: 'dis_quyi_chirchiq',    region_id: 'reg_toshkent', name_uz: 'Quyi Chirchiq tumani',        lat: 41.1167, lon: 69.3333, order: 12 },
  { id: 'dis_ohangaron',        region_id: 'reg_toshkent', name_uz: 'Ohangaron tumani',            lat: 40.9000, lon: 69.6500, order: 13 },
  { id: 'dis_piskent',          region_id: 'reg_toshkent', name_uz: 'Piskent tumani',              lat: 41.0000, lon: 69.3833, order: 14 },
  { id: 'dis_toshkent_tuman',   region_id: 'reg_toshkent', name_uz: 'Toshkent tumani',             lat: 41.2667, lon: 69.3167, order: 15 },
  { id: 'dis_urtachirchiq',     region_id: 'reg_toshkent', name_uz: 'Urtachirchiq tumani',         lat: 41.0833, lon: 69.5000, order: 16 },

  // ─── Samarqand viloyati (14 tuman) ────────────────────────────────────
  { id: 'dis_samarqand_sh',    region_id: 'reg_samarqand', name_uz: 'Samarqand shahri',            lat: 39.6542, lon: 66.9597, order: 1 },
  { id: 'dis_urgut',           region_id: 'reg_samarqand', name_uz: 'Urgut tumani',                lat: 39.4000, lon: 67.2500, order: 2 },
  { id: 'dis_kattaqorgon_sh',  region_id: 'reg_samarqand', name_uz: "Kattaqo'rg'on shahri",       lat: 39.9000, lon: 66.2500, order: 3 },
  { id: 'dis_pastdargom',      region_id: 'reg_samarqand', name_uz: "Pastdarg'om tumani",          lat: 39.5833, lon: 66.7167, order: 4 },
  { id: 'dis_bulungur',        region_id: 'reg_samarqand', name_uz: "Bulung'ur tumani",            lat: 39.7500, lon: 67.2833, order: 5 },
  { id: 'dis_toyloq',          region_id: 'reg_samarqand', name_uz: 'Toyloq tumani',               lat: 39.6000, lon: 67.0833, order: 6 },
  { id: 'dis_ishtixon',        region_id: 'reg_samarqand', name_uz: 'Ishtixon tumani',             lat: 39.9667, lon: 66.4833, order: 7 },
  { id: 'dis_payariq',         region_id: 'reg_samarqand', name_uz: 'Payariq tumani',              lat: 40.0167, lon: 66.8500, order: 8 },
  { id: 'dis_oqdaryo',         region_id: 'reg_samarqand', name_uz: "Oqdaryo tumani",              lat: 39.7833, lon: 66.6333, order: 9 },
  { id: 'dis_nurobod',         region_id: 'reg_samarqand', name_uz: 'Nurobod tumani',              lat: 39.5833, lon: 67.5500, order: 10 },
  { id: 'dis_qoshrabot',       region_id: 'reg_samarqand', name_uz: "Qo'shrabot tumani",           lat: 40.1167, lon: 66.7500, order: 11 },
  { id: 'dis_jomboy',          region_id: 'reg_samarqand', name_uz: 'Jomboy tumani',               lat: 39.8333, lon: 67.2167, order: 12 },
  { id: 'dis_narpay',          region_id: 'reg_samarqand', name_uz: 'Narpay tumani',               lat: 39.9833, lon: 66.4000, order: 13 },
  { id: 'dis_kattaqorgon_t',   region_id: 'reg_samarqand', name_uz: "Kattaqo'rg'on tumani",       lat: 39.9000, lon: 66.1500, order: 14 },

  // ─── Farg'ona viloyati (15 tuman) ────────────────────────────────────
  { id: 'dis_fargona_sh',      region_id: 'reg_fargona', name_uz: "Farg'ona shahri",               lat: 40.3842, lon: 71.7843, order: 1 },
  { id: 'dis_margilon',        region_id: 'reg_fargona', name_uz: "Marg'ilon shahri",              lat: 40.4722, lon: 71.7167, order: 2 },
  { id: 'dis_qoqon',           region_id: 'reg_fargona', name_uz: "Qo'qon shahri",                lat: 40.5333, lon: 70.9333, order: 3 },
  { id: 'dis_quvasoy',         region_id: 'reg_fargona', name_uz: 'Quvasoy shahri',               lat: 40.3000, lon: 71.9667, order: 4 },
  { id: 'dis_oltiariq',        region_id: 'reg_fargona', name_uz: 'Oltiariq tumani',              lat: 40.4000, lon: 71.4833, order: 5 },
  { id: 'dis_rishton',         region_id: 'reg_fargona', name_uz: 'Rishton tumani',               lat: 40.3500, lon: 71.2833, order: 6 },
  { id: 'dis_uchkoprik',       region_id: 'reg_fargona', name_uz: "Uchko'prik tumani",            lat: 40.5333, lon: 71.0500, order: 7 },
  { id: 'dis_bagdod',          region_id: 'reg_fargona', name_uz: "Bag'dod tumani",               lat: 40.4500, lon: 71.2167, order: 8 },
  { id: 'dis_beshariq',        region_id: 'reg_fargona', name_uz: 'Beshariq tumani',              lat: 40.5000, lon: 71.1833, order: 9 },
  { id: 'dis_buvayda',         region_id: 'reg_fargona', name_uz: 'Buvayda tumani',               lat: 40.2833, lon: 71.5000, order: 10 },
  { id: 'dis_dangara',         region_id: 'reg_fargona', name_uz: "Dang'ara tumani",              lat: 40.5167, lon: 71.4333, order: 11 },
  { id: 'dis_fargona_t',       region_id: 'reg_fargona', name_uz: "Farg'ona tumani",              lat: 40.4500, lon: 71.6833, order: 12 },
  { id: 'dis_qoshtegirmon',    region_id: 'reg_fargona', name_uz: "Qo'shtepa tumani",             lat: 40.5667, lon: 71.3500, order: 13 },
  { id: 'dis_sox',             region_id: 'reg_fargona', name_uz: "So'x tumani",                  lat: 39.9667, lon: 71.1333, order: 14 },
  { id: 'dis_toshloq',         region_id: 'reg_fargona', name_uz: "Toshloq tumani",               lat: 40.5833, lon: 71.5667, order: 15 },

  // ─── Andijon viloyati (14 tuman) ─────────────────────────────────────
  { id: 'dis_andijon_sh',      region_id: 'reg_andijon', name_uz: 'Andijon shahri',               lat: 40.7821, lon: 72.3442, order: 1 },
  { id: 'dis_asaka',           region_id: 'reg_andijon', name_uz: 'Asaka tumani',                 lat: 40.6400, lon: 72.2300, order: 2 },
  { id: 'dis_xonobod',         region_id: 'reg_andijon', name_uz: 'Xonobod shahri',               lat: 40.8000, lon: 72.9833, order: 3 },
  { id: 'dis_shahrixon',       region_id: 'reg_andijon', name_uz: 'Shahrixon tumani',             lat: 40.7167, lon: 72.0500, order: 4 },
  { id: 'dis_baliqchi',        region_id: 'reg_andijon', name_uz: 'Baliqchi tumani',              lat: 40.9333, lon: 71.9000, order: 5 },
  { id: 'dis_oltinkol',        region_id: 'reg_andijon', name_uz: "Oltinko'l tumani",             lat: 40.7667, lon: 72.1833, order: 6 },
  { id: 'dis_qorgontepa',      region_id: 'reg_andijon', name_uz: "Qo'rg'ontepa tumani",         lat: 40.7333, lon: 72.7500, order: 7 },
  { id: 'dis_boz',             region_id: 'reg_andijon', name_uz: "Bo'z tumani",                  lat: 40.5833, lon: 72.4833, order: 8 },
  { id: 'dis_buloqboshi',      region_id: 'reg_andijon', name_uz: 'Buloqboshi tumani',            lat: 40.8667, lon: 72.3167, order: 9 },
  { id: 'dis_jalaquduk',       region_id: 'reg_andijon', name_uz: "Jalaquduq tumani",             lat: 40.9000, lon: 72.6333, order: 10 },
  { id: 'dis_xojaobod',        region_id: 'reg_andijon', name_uz: "Xo'jaobod tumani",            lat: 40.6500, lon: 72.5500, order: 11 },
  { id: 'dis_marhamat',        region_id: 'reg_andijon', name_uz: 'Marhamat tumani',              lat: 40.5167, lon: 72.3000, order: 12 },
  { id: 'dis_paxtaobod',       region_id: 'reg_andijon', name_uz: 'Paxtaobod tumani',            lat: 40.5667, lon: 72.1667, order: 13 },
  { id: 'dis_ulugnar',         region_id: 'reg_andijon', name_uz: "Ulug'nor tumani",              lat: 40.9667, lon: 72.8333, order: 14 },

  // ─── Namangan viloyati (12 tuman) ────────────────────────────────────
  { id: 'dis_namangan_sh',     region_id: 'reg_namangan', name_uz: 'Namangan shahri',             lat: 40.9983, lon: 71.6726, order: 1 },
  { id: 'dis_chortoq',         region_id: 'reg_namangan', name_uz: 'Chortoq tumani',              lat: 41.0667, lon: 71.8167, order: 2 },
  { id: 'dis_chust',           region_id: 'reg_namangan', name_uz: 'Chust tumani',                lat: 41.0000, lon: 71.2333, order: 3 },
  { id: 'dis_pop',             region_id: 'reg_namangan', name_uz: 'Pop tumani',                  lat: 40.8667, lon: 71.1000, order: 4 },
  { id: 'dis_kosonsoy',        region_id: 'reg_namangan', name_uz: 'Kosonsoy tumani',             lat: 41.2500, lon: 71.5500, order: 5 },
  { id: 'dis_toraqorgon',      region_id: 'reg_namangan', name_uz: "To'raqo'rg'on tumani",       lat: 41.0000, lon: 71.5167, order: 6 },
  { id: 'dis_uchqorgon',       region_id: 'reg_namangan', name_uz: "Uchqo'rg'on tumani",         lat: 41.1167, lon: 72.0833, order: 7 },
  { id: 'dis_mingbuloq',       region_id: 'reg_namangan', name_uz: "Mingbuloq tumani",            lat: 40.8000, lon: 71.7667, order: 8 },
  { id: 'dis_namangan_t',      region_id: 'reg_namangan', name_uz: 'Namangan tumani',             lat: 40.9500, lon: 71.5500, order: 9 },
  { id: 'dis_norin',           region_id: 'reg_namangan', name_uz: "Norin tumani",                lat: 41.1667, lon: 71.3500, order: 10 },
  { id: 'dis_turakurgon',      region_id: 'reg_namangan', name_uz: "Turaqo'rg'on tumani",        lat: 40.9333, lon: 71.5000, order: 11 },
  { id: 'dis_yangiqorgon',     region_id: 'reg_namangan', name_uz: "Yangi Qo'rg'on tumani",      lat: 41.0333, lon: 71.3167, order: 12 },

  // ─── Buxoro viloyati (11 tuman) ──────────────────────────────────────
  { id: 'dis_buxoro_sh',       region_id: 'reg_buxoro', name_uz: 'Buxoro shahri',                lat: 39.7747, lon: 64.4286, order: 1 },
  { id: 'dis_gijduvon',        region_id: 'reg_buxoro', name_uz: "G'ijduvon tumani",             lat: 40.1000, lon: 64.6667, order: 2 },
  { id: 'dis_kogon_sh',        region_id: 'reg_buxoro', name_uz: 'Kogon shahri',                 lat: 39.7167, lon: 64.5500, order: 3 },
  { id: 'dis_qorakol',         region_id: 'reg_buxoro', name_uz: "Qorako'l tumani",              lat: 39.5000, lon: 63.8500, order: 4 },
  { id: 'dis_jondor',          region_id: 'reg_buxoro', name_uz: 'Jondor tumani',                lat: 39.7333, lon: 64.1833, order: 5 },
  { id: 'dis_vobkent',         region_id: 'reg_buxoro', name_uz: 'Vobkent tumani',               lat: 40.0333, lon: 64.5167, order: 6 },
  { id: 'dis_buxoro_t',        region_id: 'reg_buxoro', name_uz: 'Buxoro tumani',                lat: 39.6833, lon: 64.2833, order: 7 },
  { id: 'dis_olot',            region_id: 'reg_buxoro', name_uz: "Olot tumani",                  lat: 39.0333, lon: 63.8333, order: 8 },
  { id: 'dis_peshku',          region_id: 'reg_buxoro', name_uz: "Peshku tumani",                lat: 39.9167, lon: 64.3833, order: 9 },
  { id: 'dis_qorovulbozor',    region_id: 'reg_buxoro', name_uz: "Qorovulbozor tumani",          lat: 39.4833, lon: 64.7833, order: 10 },
  { id: 'dis_shofirkon',       region_id: 'reg_buxoro', name_uz: "Shofirkon tumani",             lat: 40.1167, lon: 64.4833, order: 11 },

  // ─── Xorazm viloyati (11 tuman) ──────────────────────────────────────
  { id: 'dis_urganch_sh',      region_id: 'reg_xorazm', name_uz: 'Urganch shahri',               lat: 41.5500, lon: 60.6333, order: 1 },
  { id: 'dis_xiva_sh',         region_id: 'reg_xorazm', name_uz: 'Xiva shahri',                  lat: 41.3783, lon: 60.3639, order: 2 },
  { id: 'dis_xonqa',           region_id: 'reg_xorazm', name_uz: 'Xonqa tumani',                 lat: 41.4833, lon: 60.7833, order: 3 },
  { id: 'dis_gurlan',          region_id: 'reg_xorazm', name_uz: 'Gurlan tumani',                lat: 41.8333, lon: 60.3833, order: 4 },
  { id: 'dis_shovot',          region_id: 'reg_xorazm', name_uz: 'Shovot tumani',                lat: 41.6833, lon: 60.3000, order: 5 },
  { id: 'dis_hazorasp',        region_id: 'reg_xorazm', name_uz: 'Hazorasp tumani',              lat: 41.3167, lon: 61.0667, order: 6 },
  { id: 'dis_bog_ot',          region_id: 'reg_xorazm', name_uz: "Bog'ot tumani",                lat: 41.7167, lon: 60.5667, order: 7 },
  { id: 'dis_kushkupir',       region_id: 'reg_xorazm', name_uz: 'Kushkupir tumani',             lat: 41.5000, lon: 60.4333, order: 8 },
  { id: 'dis_pitnak',          region_id: 'reg_xorazm', name_uz: 'Pitnak tumani',                lat: 41.5833, lon: 61.1500, order: 9 },
  { id: 'dis_tuproqqala',      region_id: 'reg_xorazm', name_uz: "Tuproqqal'a tumani",           lat: 41.6167, lon: 60.9167, order: 10 },
  { id: 'dis_yangiariq',       region_id: 'reg_xorazm', name_uz: "Yangiariq tumani",             lat: 41.7000, lon: 60.8333, order: 11 },

  // ─── Qashqadaryo viloyati (14 tuman) ─────────────────────────────────
  { id: 'dis_qarshi_sh',       region_id: 'reg_qashqadaryo', name_uz: 'Qarshi shahri',           lat: 38.8606, lon: 65.7890, order: 1 },
  { id: 'dis_shahrisabz_sh',   region_id: 'reg_qashqadaryo', name_uz: 'Shahrisabz shahri',       lat: 39.0500, lon: 66.8333, order: 2 },
  { id: 'dis_kitob',           region_id: 'reg_qashqadaryo', name_uz: 'Kitob tumani',            lat: 39.1333, lon: 66.8833, order: 3 },
  { id: 'dis_guzor',           region_id: 'reg_qashqadaryo', name_uz: "G'uzor tumani",           lat: 38.6167, lon: 66.2500, order: 4 },
  { id: 'dis_koson',           region_id: 'reg_qashqadaryo', name_uz: 'Koson tumani',            lat: 39.0333, lon: 65.5833, order: 5 },
  { id: 'dis_yakkabog',        region_id: 'reg_qashqadaryo', name_uz: "Yakkabog' tumani",        lat: 38.9833, lon: 66.6833, order: 6 },
  { id: 'dis_chiroqchi',       region_id: 'reg_qashqadaryo', name_uz: "Chiroqchi tumani",        lat: 39.0000, lon: 66.5333, order: 7 },
  { id: 'dis_dehqonobod',      region_id: 'reg_qashqadaryo', name_uz: "Dehqonobod tumani",       lat: 38.4500, lon: 66.5000, order: 8 },
  { id: 'dis_kamashi',         region_id: 'reg_qashqadaryo', name_uz: "Kamashi tumani",          lat: 38.8333, lon: 66.6167, order: 9 },
  { id: 'dis_mirishkor',       region_id: 'reg_qashqadaryo', name_uz: "Mirishkor tumani",        lat: 38.7167, lon: 65.6500, order: 10 },
  { id: 'dis_muborak',         region_id: 'reg_qashqadaryo', name_uz: "Muborak tumani",          lat: 39.2833, lon: 65.2333, order: 11 },
  { id: 'dis_nishon',          region_id: 'reg_qashqadaryo', name_uz: "Nishon tumani",           lat: 39.0167, lon: 65.3500, order: 12 },
  { id: 'dis_qasbi',           region_id: 'reg_qashqadaryo', name_uz: "Qasbi tumani",            lat: 38.7000, lon: 66.0167, order: 13 },
  { id: 'dis_shahrisabz_t',    region_id: 'reg_qashqadaryo', name_uz: "Shahrisabz tumani",       lat: 39.0167, lon: 66.7667, order: 14 },

  // ─── Surxondaryo viloyati (14 tuman) ─────────────────────────────────
  { id: 'dis_termiz_sh',       region_id: 'reg_surxondaryo', name_uz: 'Termiz shahri',           lat: 37.2242, lon: 67.2783, order: 1 },
  { id: 'dis_denov',           region_id: 'reg_surxondaryo', name_uz: 'Denov tumani',            lat: 38.2667, lon: 67.9000, order: 2 },
  { id: 'dis_shorchi',         region_id: 'reg_surxondaryo', name_uz: "Sho'rchi tumani",         lat: 37.9833, lon: 67.7833, order: 3 },
  { id: 'dis_jarqorgon',       region_id: 'reg_surxondaryo', name_uz: "Jarqo'rg'on tumani",     lat: 37.5000, lon: 67.4167, order: 4 },
  { id: 'dis_boysun',          region_id: 'reg_surxondaryo', name_uz: 'Boysun tumani',           lat: 38.2000, lon: 67.2000, order: 5 },
  { id: 'dis_angor',           region_id: 'reg_surxondaryo', name_uz: 'Angor tumani',            lat: 37.5000, lon: 67.1167, order: 6 },
  { id: 'dis_bandixon',        region_id: 'reg_surxondaryo', name_uz: 'Bandixon tumani',         lat: 37.6833, lon: 67.6667, order: 7 },
  { id: 'dis_baysun',          region_id: 'reg_surxondaryo', name_uz: 'Baysun tumani',           lat: 38.1167, lon: 67.1500, order: 8 },
  { id: 'dis_kumqurgon',       region_id: 'reg_surxondaryo', name_uz: "Qumqo'rg'on tumani",     lat: 37.8333, lon: 67.5833, order: 9 },
  { id: 'dis_muzrabot',        region_id: 'reg_surxondaryo', name_uz: 'Muzrabot tumani',         lat: 37.3833, lon: 67.7833, order: 10 },
  { id: 'dis_oltinsoy',        region_id: 'reg_surxondaryo', name_uz: "Oltinsoy tumani",         lat: 38.0167, lon: 67.5000, order: 11 },
  { id: 'dis_sariosiyo',       region_id: 'reg_surxondaryo', name_uz: "Sariosiyo tumani",        lat: 38.4167, lon: 67.7333, order: 12 },
  { id: 'dis_termiz_t',        region_id: 'reg_surxondaryo', name_uz: 'Termiz tumani',           lat: 37.3000, lon: 67.3500, order: 13 },
  { id: 'dis_uzun',            region_id: 'reg_surxondaryo', name_uz: "Uzun tumani",             lat: 37.6333, lon: 67.7167, order: 14 },

  // ─── Jizzax viloyati (12 tuman) ──────────────────────────────────────
  { id: 'dis_jizzax_sh',       region_id: 'reg_jizzax', name_uz: 'Jizzax shahri',                lat: 40.1250, lon: 67.8808, order: 1 },
  { id: 'dis_zomin',           region_id: 'reg_jizzax', name_uz: 'Zomin tumani',                 lat: 39.9667, lon: 68.4000, order: 2 },
  { id: 'dis_gallaorol',       region_id: 'reg_jizzax', name_uz: "G'allaorol tumani",            lat: 40.0333, lon: 67.5833, order: 3 },
  { id: 'dis_paxtakor',        region_id: 'reg_jizzax', name_uz: 'Paxtakor tumani',              lat: 40.3167, lon: 67.9500, order: 4 },
  { id: 'dis_arnasoy',         region_id: 'reg_jizzax', name_uz: "Arnasoy tumani",               lat: 40.4500, lon: 67.5167, order: 5 },
  { id: 'dis_baxmal',          region_id: 'reg_jizzax', name_uz: "Baxmal tumani",                lat: 39.7833, lon: 68.8167, order: 6 },
  { id: 'dis_dostlik',         region_id: 'reg_jizzax', name_uz: "Do'stlik tumani",              lat: 40.5167, lon: 68.5500, order: 7 },
  { id: 'dis_forish',          region_id: 'reg_jizzax', name_uz: "Forish tumani",                lat: 39.9167, lon: 68.0500, order: 8 },
  { id: 'dis_mirzacho_l',      region_id: 'reg_jizzax', name_uz: "Mirzacho'l tumani",           lat: 40.5500, lon: 68.8500, order: 9 },
  { id: 'dis_sharof_rashidov', region_id: 'reg_jizzax', name_uz: 'Sharof Rashidov tumani',       lat: 40.2833, lon: 68.2500, order: 10 },
  { id: 'dis_yangiobod',       region_id: 'reg_jizzax', name_uz: "Yangiobod tumani",             lat: 40.1833, lon: 68.6167, order: 11 },
  { id: 'dis_zarbdor',         region_id: 'reg_jizzax', name_uz: "Zarbdor tumani",               lat: 40.4333, lon: 68.1833, order: 12 },

  // ─── Sirdaryo viloyati (9 tuman) ─────────────────────────────────────
  { id: 'dis_guliston_sh',     region_id: 'reg_sirdaryo', name_uz: 'Guliston shahri',            lat: 40.4897, lon: 68.7842, order: 1 },
  { id: 'dis_yangiyer_sh',     region_id: 'reg_sirdaryo', name_uz: 'Yangiyer shahri',            lat: 40.2667, lon: 68.8167, order: 2 },
  { id: 'dis_shirin_sh',       region_id: 'reg_sirdaryo', name_uz: 'Shirin shahri',              lat: 40.2167, lon: 69.1333, order: 3 },
  { id: 'dis_boyovut',         region_id: 'reg_sirdaryo', name_uz: 'Boyovut tumani',             lat: 40.4167, lon: 69.0500, order: 4 },
  { id: 'dis_baxt',            region_id: 'reg_sirdaryo', name_uz: "Baxt tumani",                lat: 40.2833, lon: 68.7167, order: 5 },
  { id: 'dis_guliston_t',      region_id: 'reg_sirdaryo', name_uz: "Guliston tumani",            lat: 40.4333, lon: 68.7333, order: 6 },
  { id: 'dis_oqoltin',         region_id: 'reg_sirdaryo', name_uz: "Oqoltin tumani",             lat: 40.5333, lon: 68.6167, order: 7 },
  { id: 'dis_sardoba',         region_id: 'reg_sirdaryo', name_uz: "Sardoba tumani",             lat: 40.6167, lon: 68.3667, order: 8 },
  { id: 'dis_sayxunobod',      region_id: 'reg_sirdaryo', name_uz: "Sayxunobod tumani",          lat: 40.1667, lon: 68.9667, order: 9 },

  // ─── Navoiy viloyati (8 tuman) ───────────────────────────────────────
  { id: 'dis_navoiy_sh',       region_id: 'reg_navoiy', name_uz: 'Navoiy shahri',                lat: 40.0844, lon: 65.3792, order: 1 },
  { id: 'dis_zarafshon_sh',    region_id: 'reg_navoiy', name_uz: 'Zarafshon shahri',             lat: 41.5667, lon: 64.2000, order: 2 },
  { id: 'dis_karmana',         region_id: 'reg_navoiy', name_uz: 'Karmana tumani',               lat: 40.1333, lon: 65.3667, order: 3 },
  { id: 'dis_qiziltepa',       region_id: 'reg_navoiy', name_uz: 'Qiziltepa tumani',             lat: 40.0333, lon: 64.8167, order: 4 },
  { id: 'dis_xatirchi',        region_id: 'reg_navoiy', name_uz: 'Xatirchi tumani',              lat: 40.0333, lon: 65.9500, order: 5 },
  { id: 'dis_konimex',         region_id: 'reg_navoiy', name_uz: "Konimex tumani",               lat: 41.4833, lon: 64.7833, order: 6 },
  { id: 'dis_navbahor',        region_id: 'reg_navoiy', name_uz: "Navbahor tumani",              lat: 40.1333, lon: 65.5833, order: 7 },
  { id: 'dis_nurota',          region_id: 'reg_navoiy', name_uz: "Nurota tumani",                lat: 40.5500, lon: 65.6833, order: 8 },

  // ─── Qoraqalpog'iston Respublikasi (15 tuman) ─────────────────────────
  { id: 'dis_nukus_sh',        region_id: 'reg_qoraqalpogiston', name_uz: 'Nukus shahri',        lat: 42.4611, lon: 59.6166, order: 1 },
  { id: 'dis_xojayli',         region_id: 'reg_qoraqalpogiston', name_uz: "Xo'jayli tumani",    lat: 42.4000, lon: 59.4500, order: 2 },
  { id: 'dis_qongirot',        region_id: 'reg_qoraqalpogiston', name_uz: "Qo'ng'irot tumani",  lat: 43.0500, lon: 58.8333, order: 3 },
  { id: 'dis_beruniy',         region_id: 'reg_qoraqalpogiston', name_uz: 'Beruniy tumani',      lat: 41.6833, lon: 60.7500, order: 4 },
  { id: 'dis_tortkol',         region_id: 'reg_qoraqalpogiston', name_uz: "To'rtko'l tumani",   lat: 41.5500, lon: 61.0000, order: 5 },
  { id: 'dis_chimboy',         region_id: 'reg_qoraqalpogiston', name_uz: 'Chimboy tumani',      lat: 42.9333, lon: 59.7667, order: 6 },
  { id: 'dis_amudaryo',        region_id: 'reg_qoraqalpogiston', name_uz: 'Amudaryo tumani',     lat: 41.4333, lon: 60.3833, order: 7 },
  { id: 'dis_bozatov',         region_id: 'reg_qoraqalpogiston', name_uz: 'Bozatov tumani',      lat: 43.4833, lon: 60.1167, order: 8 },
  { id: 'dis_ellikqala',       region_id: 'reg_qoraqalpogiston', name_uz: "Ellikqal'a tumani",  lat: 41.8500, lon: 60.7333, order: 9 },
  { id: 'dis_kegeyli',         region_id: 'reg_qoraqalpogiston', name_uz: 'Kegeyli tumani',      lat: 42.7667, lon: 59.5833, order: 10 },
  { id: 'dis_muynoq',          region_id: 'reg_qoraqalpogiston', name_uz: "Mo'ynoq tumani",      lat: 43.7667, lon: 59.0167, order: 11 },
  { id: 'dis_nukus_t',         region_id: 'reg_qoraqalpogiston', name_uz: 'Nukus tumani',        lat: 42.5000, lon: 59.3000, order: 12 },
  { id: 'dis_qanliko_l',       region_id: 'reg_qoraqalpogiston', name_uz: "Qanliko'l tumani",   lat: 42.8833, lon: 60.2500, order: 13 },
  { id: 'dis_shumanay',        region_id: 'reg_qoraqalpogiston', name_uz: 'Shumanay tumani',     lat: 42.2167, lon: 59.3833, order: 14 },
  { id: 'dis_takhtakopir',     region_id: 'reg_qoraqalpogiston', name_uz: "Taxtako'pir tumani",  lat: 43.2167, lon: 59.2500, order: 15 },
];
